/* query para extraer la informacion por rangos de edad
SELECT
    CASE 
	    WHEN p.EDAD BETWEEN 15 AND 19 THEN '15-19 años'
        WHEN p.EDAD BETWEEN 20 AND 29 THEN '20-29 años'
        WHEN p.EDAD BETWEEN 30 AND 39 THEN '30-39 años'
        WHEN p.EDAD BETWEEN 40 AND 49 THEN '40-49 años'
		WHEN p.EDAD BETWEEN 50 AND 59 THEN '50-59 años'
        WHEN p.EDAD BETWEEN 60 AND 69 THEN '60-69 años'
        WHEN p.EDAD >= 70 THEN '70+ años'
        ELSE 'Desconocido'
    END AS Rango_Edad,

    COUNT(*) AS Total_Medicos,
    SUM(CASE WHEN p.SEXO = 'H' THEN 1 ELSE 0 END) AS Hombres,
    SUM(CASE WHEN p.SEXO = 'M' THEN 1 ELSE 0 END) AS Mujeres,

    -- Estados
    SUM(CASE WHEN p.NUMDEL = 1 THEN 1 ELSE 0 END) AS Aguascalientes,
    SUM(CASE WHEN p.NUMDEL = 2 THEN 1 ELSE 0 END) AS Baja_California,
    SUM(CASE WHEN p.NUMDEL = 3 THEN 1 ELSE 0 END) AS Baja_California_Sur,
    SUM(CASE WHEN p.NUMDEL = 4 THEN 1 ELSE 0 END) AS Campeche,
    SUM(CASE WHEN p.NUMDEL = 5 THEN 1 ELSE 0 END) AS Coahuila,
    SUM(CASE WHEN p.NUMDEL = 6 THEN 1 ELSE 0 END) AS Colima,
    SUM(CASE WHEN p.NUMDEL = 7 THEN 1 ELSE 0 END) AS Chiapas,
    SUM(CASE WHEN p.NUMDEL = 8 THEN 1 ELSE 0 END) AS Chihuahua,
    SUM(CASE WHEN p.NUMDEL = 9 THEN 1 ELSE 0 END) AS Nivel_Central,
    SUM(CASE WHEN p.NUMDEL = 10 THEN 1 ELSE 0 END) AS Durango,
    SUM(CASE WHEN p.NUMDEL = 11 THEN 1 ELSE 0 END) AS Guanajuato,
    SUM(CASE WHEN p.NUMDEL = 12 THEN 1 ELSE 0 END) AS Guerrero,
    SUM(CASE WHEN p.NUMDEL = 13 THEN 1 ELSE 0 END) AS Hidalgo,
    SUM(CASE WHEN p.NUMDEL = 14 THEN 1 ELSE 0 END) AS Jalisco,
    SUM(CASE WHEN p.NUMDEL = 15 THEN 1 ELSE 0 END) AS Mexico_Oriente,
    SUM(CASE WHEN p.NUMDEL = 16 THEN 1 ELSE 0 END) AS Mexico_Poniente,
    SUM(CASE WHEN p.NUMDEL = 17 THEN 1 ELSE 0 END) AS Michoacan,
    SUM(CASE WHEN p.NUMDEL = 18 THEN 1 ELSE 0 END) AS Morelos,
    SUM(CASE WHEN p.NUMDEL = 19 THEN 1 ELSE 0 END) AS Nayarit,
    SUM(CASE WHEN p.NUMDEL = 20 THEN 1 ELSE 0 END) AS Nuevo_Leon,
    SUM(CASE WHEN p.NUMDEL = 21 THEN 1 ELSE 0 END) AS Oaxaca,
    SUM(CASE WHEN p.NUMDEL = 22 THEN 1 ELSE 0 END) AS Puebla,
    SUM(CASE WHEN p.NUMDEL = 23 THEN 1 ELSE 0 END) AS Queretaro,
    SUM(CASE WHEN p.NUMDEL = 24 THEN 1 ELSE 0 END) AS Quintana_Roo,
    SUM(CASE WHEN p.NUMDEL = 25 THEN 1 ELSE 0 END) AS San_Luis_Potosi,
    SUM(CASE WHEN p.NUMDEL = 26 THEN 1 ELSE 0 END) AS Sinaloa,
    SUM(CASE WHEN p.NUMDEL = 27 THEN 1 ELSE 0 END) AS Sonora,
    SUM(CASE WHEN p.NUMDEL = 28 THEN 1 ELSE 0 END) AS Tabasco,
    SUM(CASE WHEN p.NUMDEL = 29 THEN 1 ELSE 0 END) AS Tamaulipas,
    SUM(CASE WHEN p.NUMDEL = 30 THEN 1 ELSE 0 END) AS Tlaxcala,
    SUM(CASE WHEN p.NUMDEL = 31 THEN 1 ELSE 0 END) AS Veracruz_Norte,
    SUM(CASE WHEN p.NUMDEL = 32 THEN 1 ELSE 0 END) AS Veracruz_Sur,
    SUM(CASE WHEN p.NUMDEL = 33 THEN 1 ELSE 0 END) AS Yucatan,
    SUM(CASE WHEN p.NUMDEL = 34 THEN 1 ELSE 0 END) AS Zacatecas,
    SUM(CASE WHEN p.NUMDEL IN (35, 36) THEN 1 ELSE 0 END) AS DF_Norte,
    SUM(CASE WHEN p.NUMDEL IN (37, 38) THEN 1 ELSE 0 END) AS DF_Sur

FROM personalaps.plantillaordinario p
WHERE p.PLZOCU = 1 -- Solo plazas ocupadas
AND p.DESCRIP_CLASCATEG = '1.MÉDICOS' -- Solo médicos
AND QNA = '2024017'
GROUP BY Rango_Edad
ORDER BY Rango_Edad ASC;
*/

const datosMedicos = [
	{
		"Rango_Edad" : "20-29 años",
		"Total_Medicos" : 474,
		"Hombres" : 222,
		"Mujeres" : 252,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 2,
		"Coahuila" : 4,
		"Colima" : 11,
		"Chiapas" : 51,
		"Chihuahua" : 4,
		"Nivel_Central" : 0,
		"Durango" : 4,
		"Guanajuato" : 0,
		"Guerrero" : 0,
		"Hidalgo" : 16,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 1,
		"Michoacan" : 7,
		"Morelos" : 0,
		"Nayarit" : 45,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 115,
		"Puebla" : 12,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 32,
		"Sinaloa" : 13,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 2,
		"Tlaxcala" : 8,
		"Veracruz_Norte" : 92,
		"Veracruz_Sur" : 21,
		"Yucatan" : 5,
		"Zacatecas" : 29,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "30-39 años",
		"Total_Medicos" : 1598,
		"Hombres" : 794,
		"Mujeres" : 804,
		"Aguascalientes" : 0,
		"Baja_California" : 9,
		"Baja_California_Sur" : 0,
		"Campeche" : 29,
		"Coahuila" : 29,
		"Colima" : 11,
		"Chiapas" : 214,
		"Chihuahua" : 30,
		"Nivel_Central" : 2,
		"Durango" : 28,
		"Guanajuato" : 0,
		"Guerrero" : 11,
		"Hidalgo" : 75,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 21,
		"Michoacan" : 59,
		"Morelos" : 0,
		"Nayarit" : 142,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 246,
		"Puebla" : 87,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 98,
		"Sinaloa" : 41,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 11,
		"Tlaxcala" : 164,
		"Veracruz_Norte" : 71,
		"Veracruz_Sur" : 65,
		"Yucatan" : 65,
		"Zacatecas" : 90,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "40-49 años",
		"Total_Medicos" : 1662,
		"Hombres" : 843,
		"Mujeres" : 819,
		"Aguascalientes" : 0,
		"Baja_California" : 17,
		"Baja_California_Sur" : 0,
		"Campeche" : 29,
		"Coahuila" : 39,
		"Colima" : 4,
		"Chiapas" : 274,
		"Chihuahua" : 35,
		"Nivel_Central" : 11,
		"Durango" : 51,
		"Guanajuato" : 0,
		"Guerrero" : 24,
		"Hidalgo" : 80,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 35,
		"Michoacan" : 154,
		"Morelos" : 0,
		"Nayarit" : 36,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 280,
		"Puebla" : 91,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 77,
		"Sinaloa" : 42,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 56,
		"Tlaxcala" : 68,
		"Veracruz_Norte" : 71,
		"Veracruz_Sur" : 75,
		"Yucatan" : 53,
		"Zacatecas" : 60,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "50-59 años",
		"Total_Medicos" : 993,
		"Hombres" : 566,
		"Mujeres" : 427,
		"Aguascalientes" : 0,
		"Baja_California" : 4,
		"Baja_California_Sur" : 0,
		"Campeche" : 13,
		"Coahuila" : 20,
		"Colima" : 2,
		"Chiapas" : 204,
		"Chihuahua" : 16,
		"Nivel_Central" : 5,
		"Durango" : 32,
		"Guanajuato" : 0,
		"Guerrero" : 9,
		"Hidalgo" : 38,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 13,
		"Michoacan" : 57,
		"Morelos" : 0,
		"Nayarit" : 11,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 134,
		"Puebla" : 126,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 47,
		"Sinaloa" : 19,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 16,
		"Tlaxcala" : 8,
		"Veracruz_Norte" : 78,
		"Veracruz_Sur" : 63,
		"Yucatan" : 41,
		"Zacatecas" : 37,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "60-69 años",
		"Total_Medicos" : 107,
		"Hombres" : 75,
		"Mujeres" : 32,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 1,
		"Coahuila" : 2,
		"Colima" : 0,
		"Chiapas" : 17,
		"Chihuahua" : 8,
		"Nivel_Central" : 3,
		"Durango" : 1,
		"Guanajuato" : 0,
		"Guerrero" : 1,
		"Hidalgo" : 4,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 2,
		"Michoacan" : 4,
		"Morelos" : 0,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 19,
		"Puebla" : 11,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 2,
		"Sinaloa" : 2,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 0,
		"Tlaxcala" : 4,
		"Veracruz_Norte" : 9,
		"Veracruz_Sur" : 11,
		"Yucatan" : 4,
		"Zacatecas" : 2,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "70+ años",
		"Total_Medicos" : 1,
		"Hombres" : 0,
		"Mujeres" : 1,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 0,
		"Coahuila" : 0,
		"Colima" : 0,
		"Chiapas" : 0,
		"Chihuahua" : 0,
		"Nivel_Central" : 0,
		"Durango" : 0,
		"Guanajuato" : 0,
		"Guerrero" : 0,
		"Hidalgo" : 0,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 0,
		"Michoacan" : 0,
		"Morelos" : 0,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 0,
		"Puebla" : 0,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 0,
		"Sinaloa" : 0,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 0,
		"Tlaxcala" : 1,
		"Veracruz_Norte" : 0,
		"Veracruz_Sur" : 0,
		"Yucatan" : 0,
		"Zacatecas" : 0,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	}
];
