/* query para extraer la informacion por rangos de edad
SELECT
    CASE 
	    WHEN p.EDAD BETWEEN 15 AND 19 THEN '15-19 años'
        WHEN p.EDAD BETWEEN 20 AND 29 THEN '20-29 años'
        WHEN p.EDAD BETWEEN 30 AND 39 THEN '30-39 años'
        WHEN p.EDAD BETWEEN 40 AND 49 THEN '40-49 años'
		WHEN p.EDAD BETWEEN 50 AND 59 THEN '50-59 años'
        WHEN p.EDAD BETWEEN 60 AND 69 THEN '60-69 años'
        WHEN p.EDAD >= 70 THEN '70+ años'
        ELSE 'Desconocido'
    END AS Rango_Edad,

    COUNT(*) AS Total_Medicos,
    SUM(CASE WHEN p.SEXO = 'H' THEN 1 ELSE 0 END) AS Hombres,
    SUM(CASE WHEN p.SEXO = 'M' THEN 1 ELSE 0 END) AS Mujeres,

    -- Estados
    SUM(CASE WHEN p.NUMDEL = 1 THEN 1 ELSE 0 END) AS Aguascalientes,
    SUM(CASE WHEN p.NUMDEL = 2 THEN 1 ELSE 0 END) AS Baja_California,
    SUM(CASE WHEN p.NUMDEL = 3 THEN 1 ELSE 0 END) AS Baja_California_Sur,
    SUM(CASE WHEN p.NUMDEL = 4 THEN 1 ELSE 0 END) AS Campeche,
    SUM(CASE WHEN p.NUMDEL = 5 THEN 1 ELSE 0 END) AS Coahuila,
    SUM(CASE WHEN p.NUMDEL = 6 THEN 1 ELSE 0 END) AS Colima,
    SUM(CASE WHEN p.NUMDEL = 7 THEN 1 ELSE 0 END) AS Chiapas,
    SUM(CASE WHEN p.NUMDEL = 8 THEN 1 ELSE 0 END) AS Chihuahua,
    SUM(CASE WHEN p.NUMDEL = 9 THEN 1 ELSE 0 END) AS Nivel_Central,
    SUM(CASE WHEN p.NUMDEL = 10 THEN 1 ELSE 0 END) AS Durango,
    SUM(CASE WHEN p.NUMDEL = 11 THEN 1 ELSE 0 END) AS Guanajuato,
    SUM(CASE WHEN p.NUMDEL = 12 THEN 1 ELSE 0 END) AS Guerrero,
    SUM(CASE WHEN p.NUMDEL = 13 THEN 1 ELSE 0 END) AS Hidalgo,
    SUM(CASE WHEN p.NUMDEL = 14 THEN 1 ELSE 0 END) AS Jalisco,
    SUM(CASE WHEN p.NUMDEL = 15 THEN 1 ELSE 0 END) AS Mexico_Oriente,
    SUM(CASE WHEN p.NUMDEL = 16 THEN 1 ELSE 0 END) AS Mexico_Poniente,
    SUM(CASE WHEN p.NUMDEL = 17 THEN 1 ELSE 0 END) AS Michoacan,
    SUM(CASE WHEN p.NUMDEL = 18 THEN 1 ELSE 0 END) AS Morelos,
    SUM(CASE WHEN p.NUMDEL = 19 THEN 1 ELSE 0 END) AS Nayarit,
    SUM(CASE WHEN p.NUMDEL = 20 THEN 1 ELSE 0 END) AS Nuevo_Leon,
    SUM(CASE WHEN p.NUMDEL = 21 THEN 1 ELSE 0 END) AS Oaxaca,
    SUM(CASE WHEN p.NUMDEL = 22 THEN 1 ELSE 0 END) AS Puebla,
    SUM(CASE WHEN p.NUMDEL = 23 THEN 1 ELSE 0 END) AS Queretaro,
    SUM(CASE WHEN p.NUMDEL = 24 THEN 1 ELSE 0 END) AS Quintana_Roo,
    SUM(CASE WHEN p.NUMDEL = 25 THEN 1 ELSE 0 END) AS San_Luis_Potosi,
    SUM(CASE WHEN p.NUMDEL = 26 THEN 1 ELSE 0 END) AS Sinaloa,
    SUM(CASE WHEN p.NUMDEL = 27 THEN 1 ELSE 0 END) AS Sonora,
    SUM(CASE WHEN p.NUMDEL = 28 THEN 1 ELSE 0 END) AS Tabasco,
    SUM(CASE WHEN p.NUMDEL = 29 THEN 1 ELSE 0 END) AS Tamaulipas,
    SUM(CASE WHEN p.NUMDEL = 30 THEN 1 ELSE 0 END) AS Tlaxcala,
    SUM(CASE WHEN p.NUMDEL = 31 THEN 1 ELSE 0 END) AS Veracruz_Norte,
    SUM(CASE WHEN p.NUMDEL = 32 THEN 1 ELSE 0 END) AS Veracruz_Sur,
    SUM(CASE WHEN p.NUMDEL = 33 THEN 1 ELSE 0 END) AS Yucatan,
    SUM(CASE WHEN p.NUMDEL = 34 THEN 1 ELSE 0 END) AS Zacatecas,
    SUM(CASE WHEN p.NUMDEL IN (35, 36) THEN 1 ELSE 0 END) AS DF_Norte,
    SUM(CASE WHEN p.NUMDEL IN (37, 38) THEN 1 ELSE 0 END) AS DF_Sur

FROM personalaps.plantillaordinario p
WHERE p.PLZOCU = 1 -- Solo plazas ocupadas
AND p.DESCRIP_CLASCATEG = '1.MÉDICOS' -- Solo médicos
AND p.QNA = '2024017'
AND p.NUMDEL = '27'
AND p.DELEGACION = 'Sonora'
GROUP BY Rango_Edad
ORDER BY Rango_Edad ASC;
*/

const datosMedicos = [
	{
		"Rango_Edad" : "20-29 años",
		"Total_Medicos" : 7,
		"Hombres" : 4,
		"Mujeres" : 3,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 0,
		"Coahuila" : 0,
		"Colima" : 0,
		"Chiapas" : 0,
		"Chihuahua" : 0,
		"Nivel_Central" : 0,
		"Durango" : 0,
		"Guanajuato" : 0,
		"Guerrero" : 0,
		"Hidalgo" : 0,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 0,
		"Michoacan" : 0,
		"Morelos" : 0,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 7,
		"Puebla" : 0,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 0,
		"Sinaloa" : 0,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 0,
		"Tlaxcala" : 0,
		"Veracruz_Norte" : 0,
		"Veracruz_Sur" : 0,
		"Yucatan" : 0,
		"Zacatecas" : 0,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "30-39 años",
		"Total_Medicos" : 334,
		"Hombres" : 157,
		"Mujeres" : 177,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 0,
		"Coahuila" : 0,
		"Colima" : 0,
		"Chiapas" : 0,
		"Chihuahua" : 0,
		"Nivel_Central" : 0,
		"Durango" : 0,
		"Guanajuato" : 0,
		"Guerrero" : 0,
		"Hidalgo" : 0,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 0,
		"Michoacan" : 0,
		"Morelos" : 0,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 334,
		"Puebla" : 0,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 0,
		"Sinaloa" : 0,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 0,
		"Tlaxcala" : 0,
		"Veracruz_Norte" : 0,
		"Veracruz_Sur" : 0,
		"Yucatan" : 0,
		"Zacatecas" : 0,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "40-49 años",
		"Total_Medicos" : 525,
		"Hombres" : 259,
		"Mujeres" : 266,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 0,
		"Coahuila" : 0,
		"Colima" : 0,
		"Chiapas" : 0,
		"Chihuahua" : 0,
		"Nivel_Central" : 0,
		"Durango" : 0,
		"Guanajuato" : 0,
		"Guerrero" : 0,
		"Hidalgo" : 0,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 0,
		"Michoacan" : 0,
		"Morelos" : 0,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 525,
		"Puebla" : 0,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 0,
		"Sinaloa" : 0,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 0,
		"Tlaxcala" : 0,
		"Veracruz_Norte" : 0,
		"Veracruz_Sur" : 0,
		"Yucatan" : 0,
		"Zacatecas" : 0,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "50-59 años",
		"Total_Medicos" : 167,
		"Hombres" : 99,
		"Mujeres" : 68,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 0,
		"Coahuila" : 0,
		"Colima" : 0,
		"Chiapas" : 0,
		"Chihuahua" : 0,
		"Nivel_Central" : 0,
		"Durango" : 0,
		"Guanajuato" : 0,
		"Guerrero" : 0,
		"Hidalgo" : 0,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 0,
		"Michoacan" : 0,
		"Morelos" : 0,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 167,
		"Puebla" : 0,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 0,
		"Sinaloa" : 0,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 0,
		"Tlaxcala" : 0,
		"Veracruz_Norte" : 0,
		"Veracruz_Sur" : 0,
		"Yucatan" : 0,
		"Zacatecas" : 0,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "60-69 años",
		"Total_Medicos" : 43,
		"Hombres" : 29,
		"Mujeres" : 14,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 0,
		"Coahuila" : 0,
		"Colima" : 0,
		"Chiapas" : 0,
		"Chihuahua" : 0,
		"Nivel_Central" : 0,
		"Durango" : 0,
		"Guanajuato" : 0,
		"Guerrero" : 0,
		"Hidalgo" : 0,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 0,
		"Michoacan" : 0,
		"Morelos" : 0,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 43,
		"Puebla" : 0,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 0,
		"Sinaloa" : 0,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 0,
		"Tlaxcala" : 0,
		"Veracruz_Norte" : 0,
		"Veracruz_Sur" : 0,
		"Yucatan" : 0,
		"Zacatecas" : 0,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	},
	{
		"Rango_Edad" : "70+ años",
		"Total_Medicos" : 1,
		"Hombres" : 0,
		"Mujeres" : 1,
		"Aguascalientes" : 0,
		"Baja_California" : 0,
		"Baja_California_Sur" : 0,
		"Campeche" : 0,
		"Coahuila" : 0,
		"Colima" : 0,
		"Chiapas" : 0,
		"Chihuahua" : 0,
		"Nivel_Central" : 0,
		"Durango" : 0,
		"Guanajuato" : 0,
		"Guerrero" : 0,
		"Hidalgo" : 0,
		"Jalisco" : 0,
		"Mexico_Oriente" : 0,
		"Mexico_Poniente" : 0,
		"Michoacan" : 0,
		"Morelos" : 0,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 1,
		"Puebla" : 0,
		"Queretaro" : 0,
		"Quintana_Roo" : 0,
		"San_Luis_Potosi" : 0,
		"Sinaloa" : 0,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 0,
		"Tlaxcala" : 0,
		"Veracruz_Norte" : 0,
		"Veracruz_Sur" : 0,
		"Yucatan" : 0,
		"Zacatecas" : 0,
		"DF_Norte" : 0,
		"DF_Sur" : 0
	}
];
