/* query para crear la tabla plazas ocupadas y vacantes por OOAD ejecutar el siguiente query

SELECT
	p.NUMDEL,
	p.DELEGACION,
	COUNT(DISTINCT p.DEPENDENCIA) AS TOTAL_UNIDADES,
	SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) AS OCUPADAS,
	SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) AS VACANTES,
	ROUND(SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) * 100.0 / 
		NULLIF(SUM(CASE WHEN p.PLZOCU = 1 OR p.PLZVAC = 1 THEN 1 ELSE 0 END), 0), 2) AS PORCENTAJE_OCUPADAS,
	ROUND(SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) * 100.0 / 
		NULLIF(SUM(CASE WHEN p.PLZOCU = 1 OR p.PLZVAC = 1 THEN 1 ELSE 0 END), 0), 2) AS PORCENTAJE_VACANTES
FROM 
	personalaps.plantillaordinario p
WHERE 
	p.DESCRIP_CLASCATEG = '1.MÉDICOS'
AND p.QNA = '2024017'
AND p.NUMDEL = '27'
AND p.DELEGACION = 'Sonora'
GROUP BY
	p.NUMDEL, p.DELEGACION
ORDER BY
	p.NUMDEL; 

*/

const datosDelegaciones = [
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"TOTAL_UNIDADES" : 31,
		"OCUPADAS" : 1077,
		"VACANTES" : 46,
		"PORCENTAJE_OCUPADAS" : 95.90,
		"PORCENTAJE_VACANTES" : 4.10
	}
];

/* query para extraer esta información del modal desagregado
SELECT 
    p.NUMDEL, 
    p.DELEGACION, 
    p.CATEGORIA AS CATEGORIA, 
    p.DESCRIP_CLASCATEG AS DESCRIPCION,
    COUNT(*) AS VACANTES
FROM 
    personalaps.plantillaordinario p
WHERE 
    p.DESCRIP_CLASCATEG = '1.MÉDICOS'
    AND p.QNA = '2024017'
    AND p.NUMDEL = '27'
	AND p.DELEGACION = 'Sonora'
    AND p.PLZVAC = 1
GROUP BY 
    p.NUMDEL, p.DELEGACION, p.CATEGORIA, p.DESCRIP_CLASCATEG
ORDER BY 
    p.NUMDEL, p.CATEGORIA;
*/
const datosDelegacionesDesagregado = [
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 28
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	}
];