/*Extraer este es un problema pero estos son los querys aplicados paso por paso para hacerlo

-- Numero 1

CREATE TABLE procesado.plazas_vacantes_por_estado_TOTAL AS
SELECT
    p.NUMDEL,
    CASE
        WHEN p.NUMDEL IN ('31', '32') THEN '30' -- Agrupa Veracruz Norte y Sur como 30
        WHEN p.NUMDEL IN ('35', '36', '37', '38') THEN '09' -- Agrupa Ciudad de México (DF Norte y Sur) como 09
        WHEN p.NUMDEL IN ('15', '16') THEN '15' -- Agrupa México Oriente y Poniente como 15
        ELSE p.NUMDEL -- Deja los demás estados igual
    END AS NUMELINEGI,
    p.DELEGACION,
    COUNT(DISTINCT p.DEPENDENCIA) AS TOTAL_UNIDADES,
    SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) AS OCUPADAS,
    SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) AS VACANTES
FROM
    personalaps.plantillaordinario p
WHERE DESCRIP_CLASCATEG = '1.MÉDICOS'
AND p.QNA = '2024017'
GROUP BY
    NUMELINEGI, p.NUMDEL, p.DELEGACION
ORDER BY
    NUMELINEGI, p.NUMDEL;

SELECT * FROM procesado.plazas_vacantes_por_estado_TOTAL;


-- Numero 2

UPDATE procesado.plazas_vacantes_por_estado_TOTAL
SET NUMELINEGI = 
    CASE 
        WHEN DELEGACION = 'Michoacán' THEN '16'
        WHEN DELEGACION = 'Morelos' THEN '17'
        WHEN DELEGACION = 'Nayarit' THEN '18'
        WHEN DELEGACION = 'Nuevo León' THEN '19'
        WHEN DELEGACION = 'Oaxaca' THEN '20'
        WHEN DELEGACION = 'Puebla' THEN '21'
        WHEN DELEGACION = 'Querétaro' THEN '22'
        WHEN DELEGACION = 'Quintana Roo' THEN '23'
        WHEN DELEGACION = 'San Luis Potosí' THEN '24'
        WHEN DELEGACION = 'Sinaloa' THEN '25'
        WHEN DELEGACION = 'Sonora' THEN '26'
        WHEN DELEGACION = 'Tabasco' THEN '27'
        WHEN DELEGACION = 'Tamaulipas' THEN '28'
        WHEN DELEGACION = 'Tlaxcala' THEN '29'
        WHEN DELEGACION = 'Veracruz Norte' THEN '30'
        WHEN DELEGACION = 'Veracruz Sur' THEN '30'
        WHEN DELEGACION = 'Yucatán' THEN '31'
        WHEN DELEGACION = 'Zacatecas' THEN '32'
        ELSE NUMELINEGI
    END
WHERE DELEGACION IN ('Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 
                     'Puebla', 'Querétaro', 'Quintana Roo', 'San Luis Potosí', 
                     'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 
                     'Veracruz Norte', 'Veracruz Sur', 'Yucatán', 'Zacatecas');


-- Numero 3

CREATE TABLE procesado.vacantes_estado_densidad_poblacional_TOTAL AS
SELECT
    CASE
        -- Agrupar Veracruz Norte y Sur bajo NUMELINEGI 30
        WHEN pvpe.NUMELINEGI = '30' THEN '30'
        -- Agrupar Ciudad de México (DF Norte y Sur) bajo NUMELINEGI 09
        WHEN pvpe.NUMELINEGI = '09' THEN '09'
        -- Agrupar México Oriente y Poniente bajo NUMELINEGI 15
        WHEN pvpe.NUMELINEGI = '15' THEN '15'
        ELSE pvpe.NUMELINEGI
    END AS NUMELINEGI,
    CASE
        -- Renombrar Veracruz agrupado
        WHEN pvpe.NUMELINEGI = '30' THEN 'Veracruz'
        -- Renombrar Ciudad de México agrupado
        WHEN pvpe.NUMELINEGI = '09' THEN 'Ciudad de México'
        -- Renombrar México agrupado
        WHEN pvpe.NUMELINEGI = '15' THEN 'Estado de México'
        ELSE pvpe.DELEGACION
    END AS DELEGACION,
    SUM(pvpe.TOTAL_UNIDADES) AS TOTAL_UNIDADES,
    SUM(pvpe.OCUPADAS) AS OCUPADAS,
    SUM(pvpe.VACANTES) AS VACANTES,
    SUM(catalogo.imss) AS DERECHOHABIENTES
FROM
    procesado.plazas_vacantes_por_estado_TOTAL pvpe
LEFT JOIN
    personalaps.catalogo_derechohabiencia_estado catalogo
    ON pvpe.NUMELINEGI = catalogo.numero_delegacion
GROUP BY
    NUMELINEGI, DELEGACION
ORDER BY
    NUMELINEGI;

SELECT *  FROM procesado.vacantes_estado_densidad_poblacional_TOTAL;


-- Numero 4

CREATE TABLE procesado.vacantes_estado_densidad_poblacional_agrupado_TOTAL AS
SELECT 
    NUMELINEGI,
    DELEGACION,
    SUM(TOTAL_UNIDADES) AS TOTAL_UNIDADES,
    SUM(VACANTES) AS PLAZAS_VACANTES,
    SUM(OCUPADAS) AS PLAZAS_OCUPADAS,
    MAX(DERECHOHABIENTES) AS DERECHOHABIENTES -- Obtiene cualquier valor (ya que son iguales)
FROM 
    procesado.vacantes_estado_densidad_poblacional_TOTAL
GROUP BY 
    NUMELINEGI, DELEGACION
ORDER BY 
    NUMELINEGI;

SELECT DELEGACION, DERECHOHABIENTES, PLAZAS_OCUPADAS, PLAZAS_VACANTES FROM procesado.vacantes_estado_densidad_poblacional_agrupado_TOTAL;

*/

// 📌 Array de datos SIN base de datos
const datos = [
	{
		"DELEGACION" : "Baja California",
		"DERECHOHABIENTES" : 19862,
		"PLAZAS_OCUPADAS" : 236,
		"PLAZAS_VACANTES" : 31
	},
	{
		"DELEGACION" : "Campeche",
		"DERECHOHABIENTES" : 8950,
		"PLAZAS_OCUPADAS" : 368,
		"PLAZAS_VACANTES" : 56
	},
	{
		"DELEGACION" : "Coahuila",
		"DERECHOHABIENTES" : 12289,
		"PLAZAS_OCUPADAS" : 587,
		"PLAZAS_VACANTES" : 104
	},
	{
		"DELEGACION" : "Colima",
		"DERECHOHABIENTES" : 2774,
		"PLAZAS_OCUPADAS" : 106,
		"PLAZAS_VACANTES" : 19
	},
	{
		"DELEGACION" : "Chiapas",
		"DERECHOHABIENTES" : 169403,
		"PLAZAS_OCUPADAS" : 2500,
		"PLAZAS_VACANTES" : 567
	},
	{
		"DELEGACION" : "Chihuahua",
		"DERECHOHABIENTES" : 31733,
		"PLAZAS_OCUPADAS" : 576,
		"PLAZAS_VACANTES" : 218
	},
	{
		"DELEGACION" : "Ciudad de México",
		"DERECHOHABIENTES" : 21158,
		"PLAZAS_OCUPADAS" : 212,
		"PLAZAS_VACANTES" : 209
	},
	{
		"DELEGACION" : "Durango",
		"DERECHOHABIENTES" : 16703,
		"PLAZAS_OCUPADAS" : 615,
		"PLAZAS_VACANTES" : 229
	},
	{
		"DELEGACION" : "Guerrero",
		"DERECHOHABIENTES" : 36293,
		"PLAZAS_OCUPADAS" : 200,
		"PLAZAS_VACANTES" : 43
	},
	{
		"DELEGACION" : "Hidalgo",
		"DERECHOHABIENTES" : 22969,
		"PLAZAS_OCUPADAS" : 1133,
		"PLAZAS_VACANTES" : 163
	},
	{
		"DELEGACION" : "Estado de México",
		"DERECHOHABIENTES" : 66031,
		"PLAZAS_OCUPADAS" : 331,
		"PLAZAS_VACANTES" : 71
	},
	{
		"DELEGACION" : "Michoacán",
		"DERECHOHABIENTES" : 41892,
		"PLAZAS_OCUPADAS" : 1381,
		"PLAZAS_VACANTES" : 303
	},
	{
		"DELEGACION" : "Nayarit",
		"DERECHOHABIENTES" : 21313,
		"PLAZAS_OCUPADAS" : 908,
		"PLAZAS_VACANTES" : 64
	},
	{
		"DELEGACION" : "Oaxaca",
		"DERECHOHABIENTES" : 97052,
		"PLAZAS_OCUPADAS" : 2594,
		"PLAZAS_VACANTES" : 310
	},
	{
		"DELEGACION" : "Puebla",
		"DERECHOHABIENTES" : 54956,
		"PLAZAS_OCUPADAS" : 1517,
		"PLAZAS_VACANTES" : 357
	},
	{
		"DELEGACION" : "San Luis Potosí",
		"DERECHOHABIENTES" : 43932,
		"PLAZAS_OCUPADAS" : 1157,
		"PLAZAS_VACANTES" : 379
	},
	{
		"DELEGACION" : "Sinaloa",
		"DERECHOHABIENTES" : 18879,
		"PLAZAS_OCUPADAS" : 528,
		"PLAZAS_VACANTES" : 98
	},
	{
		"DELEGACION" : "Tamaulipas",
		"DERECHOHABIENTES" : 16284,
		"PLAZAS_OCUPADAS" : 572,
		"PLAZAS_VACANTES" : 152
	},
	{
		"DELEGACION" : "Tlaxcala",
		"DERECHOHABIENTES" : 4519,
		"PLAZAS_OCUPADAS" : 900,
		"PLAZAS_VACANTES" : 8
	},
	{
		"DELEGACION" : "Veracruz",
		"DERECHOHABIENTES" : 108127,
		"PLAZAS_OCUPADAS" : 1911,
		"PLAZAS_VACANTES" : 431
	},
	{
		"DELEGACION" : "Yucatán",
		"DERECHOHABIENTES" : 26576,
		"PLAZAS_OCUPADAS" : 786,
		"PLAZAS_VACANTES" : 101
	},
	{
		"DELEGACION" : "Zacatecas",
		"DERECHOHABIENTES" : 14392,
		"PLAZAS_OCUPADAS" : 1148,
		"PLAZAS_VACANTES" : 276
	}
];

/*
Query para extraer esta informacion de la tabla plazas ocupadas y vacantes por categoria 

SELECT 
    p.CATEGORIA,
    COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) AS PLAZAS_OCUPADAS,
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) AS PLAZAS_VACANTES,
    (COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) - 
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END)) AS DIFERENCIA,
    ROUND(
    COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) * 100.0 /
    NULLIF(COUNT(p.MATRICULA), 0), 2
) AS PORCENTAJE_OCUPACION
FROM 
    personalaps.plantillaordinario p
WHERE p.DESCRIP_CLASCATEG = "1.MÉDICOS"
AND p.QNA = '2024017'
GROUP BY 
    p.CATEGORIA
ORDER BY 
    PLAZAS_VACANTES DESC;
*/

const datos8 = [
	{
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"PLAZAS_OCUPADAS" : 1182,
		"PLAZAS_VACANTES" : 1215,
		"DIFERENCIA" : -33,
		"PORCENTAJE_OCUPACION" : 49.31
	},
	{
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"PLAZAS_OCUPADAS" : 3150,
		"PLAZAS_VACANTES" : 904,
		"DIFERENCIA" : 2246,
		"PORCENTAJE_OCUPACION" : 77.70
	},
	{
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"PLAZAS_OCUPADAS" : 2577,
		"PLAZAS_VACANTES" : 665,
		"DIFERENCIA" : 1912,
		"PORCENTAJE_OCUPACION" : 79.49
	},
	{
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"PLAZAS_OCUPADAS" : 3215,
		"PLAZAS_VACANTES" : 136,
		"DIFERENCIA" : 3079,
		"PORCENTAJE_OCUPACION" : 95.94
	},
	{
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"PLAZAS_OCUPADAS" : 1921,
		"PLAZAS_VACANTES" : 120,
		"DIFERENCIA" : 1801,
		"PORCENTAJE_OCUPACION" : 94.12
	},
	{
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"PLAZAS_OCUPADAS" : 113,
		"PLAZAS_VACANTES" : 73,
		"DIFERENCIA" : 40,
		"PORCENTAJE_OCUPACION" : 60.75
	},
	{
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"PLAZAS_OCUPADAS" : 112,
		"PLAZAS_VACANTES" : 68,
		"DIFERENCIA" : 44,
		"PORCENTAJE_OCUPACION" : 62.22
	},
	{
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"PLAZAS_OCUPADAS" : 137,
		"PLAZAS_VACANTES" : 61,
		"DIFERENCIA" : 76,
		"PORCENTAJE_OCUPACION" : 69.19
	},
	{
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"PLAZAS_OCUPADAS" : 150,
		"PLAZAS_VACANTES" : 53,
		"DIFERENCIA" : 97,
		"PORCENTAJE_OCUPACION" : 73.89
	},
	{
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"PLAZAS_OCUPADAS" : 129,
		"PLAZAS_VACANTES" : 50,
		"DIFERENCIA" : 79,
		"PORCENTAJE_OCUPACION" : 72.07
	},
	{
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"PLAZAS_OCUPADAS" : 1275,
		"PLAZAS_VACANTES" : 49,
		"DIFERENCIA" : 1226,
		"PORCENTAJE_OCUPACION" : 96.30
	},
	{
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"PLAZAS_OCUPADAS" : 73,
		"PLAZAS_VACANTES" : 42,
		"DIFERENCIA" : 31,
		"PORCENTAJE_OCUPACION" : 63.48
	},
	{
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"PLAZAS_OCUPADAS" : 681,
		"PLAZAS_VACANTES" : 39,
		"DIFERENCIA" : 642,
		"PORCENTAJE_OCUPACION" : 94.58
	},
	{
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"PLAZAS_OCUPADAS" : 163,
		"PLAZAS_VACANTES" : 35,
		"DIFERENCIA" : 128,
		"PORCENTAJE_OCUPACION" : 82.32
	},
	{
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"PLAZAS_OCUPADAS" : 895,
		"PLAZAS_VACANTES" : 31,
		"DIFERENCIA" : 864,
		"PORCENTAJE_OCUPACION" : 96.65
	},
	{
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"PLAZAS_OCUPADAS" : 37,
		"PLAZAS_VACANTES" : 27,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 57.81
	},
	{
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"PLAZAS_OCUPADAS" : 33,
		"PLAZAS_VACANTES" : 27,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 55.00
	},
	{
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"PLAZAS_OCUPADAS" : 112,
		"PLAZAS_VACANTES" : 24,
		"DIFERENCIA" : 88,
		"PORCENTAJE_OCUPACION" : 82.35
	},
	{
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"PLAZAS_OCUPADAS" : 61,
		"PLAZAS_VACANTES" : 24,
		"DIFERENCIA" : 37,
		"PORCENTAJE_OCUPACION" : 71.76
	},
	{
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"PLAZAS_OCUPADAS" : 479,
		"PLAZAS_VACANTES" : 24,
		"DIFERENCIA" : 455,
		"PORCENTAJE_OCUPACION" : 95.23
	},
	{
		"CATEGORIA" : "SECRETARIA E2",
		"PLAZAS_OCUPADAS" : 77,
		"PLAZAS_VACANTES" : 22,
		"DIFERENCIA" : 55,
		"PORCENTAJE_OCUPACION" : 77.78
	},
	{
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"PLAZAS_OCUPADAS" : 41,
		"PLAZAS_VACANTES" : 22,
		"DIFERENCIA" : 19,
		"PORCENTAJE_OCUPACION" : 65.08
	},
	{
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"PLAZAS_OCUPADAS" : 32,
		"PLAZAS_VACANTES" : 22,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 59.26
	},
	{
		"CATEGORIA" : "TRABAJADORA SOCIAL HR 80",
		"PLAZAS_OCUPADAS" : 165,
		"PLAZAS_VACANTES" : 16,
		"DIFERENCIA" : 149,
		"PORCENTAJE_OCUPACION" : 91.16
	},
	{
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"PLAZAS_OCUPADAS" : 39,
		"PLAZAS_VACANTES" : 16,
		"DIFERENCIA" : 23,
		"PORCENTAJE_OCUPACION" : 70.91
	},
	{
		"CATEGORIA" : "LABORATORISTA HR 80",
		"PLAZAS_OCUPADAS" : 252,
		"PLAZAS_VACANTES" : 16,
		"DIFERENCIA" : 236,
		"PORCENTAJE_OCUPACION" : 94.03
	},
	{
		"CATEGORIA" : "ANALISTA E2",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 16,
		"DIFERENCIA" : -3,
		"PORCENTAJE_OCUPACION" : 44.83
	},
	{
		"CATEGORIA" : "AUX ALMACEN RURAL E0",
		"PLAZAS_OCUPADAS" : 92,
		"PLAZAS_VACANTES" : 14,
		"DIFERENCIA" : 78,
		"PORCENTAJE_OCUPACION" : 86.79
	},
	{
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 34,
		"PLAZAS_VACANTES" : 13,
		"DIFERENCIA" : 21,
		"PORCENTAJE_OCUPACION" : 72.34
	},
	{
		"CATEGORIA" : "ANALISTA SISTEMAS RURAL E0",
		"PLAZAS_OCUPADAS" : 39,
		"PLAZAS_VACANTES" : 13,
		"DIFERENCIA" : 26,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "N56 SUPERV MED PROG RURAL 80",
		"PLAZAS_OCUPADAS" : 40,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : 28,
		"PORCENTAJE_OCUPACION" : 76.92
	},
	{
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"PLAZAS_OCUPADAS" : 29,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 70.73
	},
	{
		"CATEGORIA" : "N41 JEFE ENF HR 80",
		"PLAZAS_OCUPADAS" : 59,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : 47,
		"PORCENTAJE_OCUPACION" : 83.10
	},
	{
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"PLAZAS_OCUPADAS" : 41,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : 29,
		"PORCENTAJE_OCUPACION" : 77.36
	},
	{
		"CATEGORIA" : "CHOFER RURAL E0",
		"PLAZAS_OCUPADAS" : 54,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : 42,
		"PORCENTAJE_OCUPACION" : 81.82
	},
	{
		"CATEGORIA" : "N26 TEC RURAL SALUD 80",
		"PLAZAS_OCUPADAS" : 22,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 64.71
	},
	{
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"PLAZAS_OCUPADAS" : 79,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : 67,
		"PORCENTAJE_OCUPACION" : 86.81
	},
	{
		"CATEGORIA" : "N26 ANALISTA SISTEMAS RURAL 80",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 58.62
	},
	{
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"PLAZAS_OCUPADAS" : 29,
		"PLAZAS_VACANTES" : 11,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 72.50
	},
	{
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"PLAZAS_OCUPADAS" : 59,
		"PLAZAS_VACANTES" : 10,
		"DIFERENCIA" : 49,
		"PORCENTAJE_OCUPACION" : 85.51
	},
	{
		"CATEGORIA" : "PSICOLOGO HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 74,
		"PLAZAS_VACANTES" : 10,
		"DIFERENCIA" : 64,
		"PORCENTAJE_OCUPACION" : 88.10
	},
	{
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"PLAZAS_OCUPADAS" : 53,
		"PLAZAS_VACANTES" : 10,
		"DIFERENCIA" : 43,
		"PORCENTAJE_OCUPACION" : 84.13
	},
	{
		"CATEGORIA" : "CITOTECNOLOGO HR 80",
		"PLAZAS_OCUPADAS" : 68,
		"PLAZAS_VACANTES" : 10,
		"DIFERENCIA" : 58,
		"PORCENTAJE_OCUPACION" : 87.18
	},
	{
		"CATEGORIA" : "N46 SUPERVISOR ENF RURAL 80",
		"PLAZAS_OCUPADAS" : 41,
		"PLAZAS_VACANTES" : 9,
		"DIFERENCIA" : 32,
		"PORCENTAJE_OCUPACION" : 82.00
	},
	{
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"PLAZAS_OCUPADAS" : 200,
		"PLAZAS_VACANTES" : 9,
		"DIFERENCIA" : 191,
		"PORCENTAJE_OCUPACION" : 95.69
	},
	{
		"CATEGORIA" : "ADMINISTRADOR HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 37,
		"PLAZAS_VACANTES" : 9,
		"DIFERENCIA" : 28,
		"PORCENTAJE_OCUPACION" : 80.43
	},
	{
		"CATEGORIA" : "N41 RESIDENTE CONS HR 80",
		"PLAZAS_OCUPADAS" : 35,
		"PLAZAS_VACANTES" : 9,
		"DIFERENCIA" : 26,
		"PORCENTAJE_OCUPACION" : 79.55
	},
	{
		"CATEGORIA" : "N49 LIDER PROYECTO B   80",
		"PLAZAS_OCUPADAS" : 20,
		"PLAZAS_VACANTES" : 8,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 71.43
	},
	{
		"CATEGORIA" : "NUTRICIONISTA DIET HR 80",
		"PLAZAS_OCUPADAS" : 103,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 96,
		"PORCENTAJE_OCUPACION" : 93.64
	},
	{
		"CATEGORIA" : "N53 RESPONSABLE PROY A 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : -6,
		"PORCENTAJE_OCUPACION" : 12.50
	},
	{
		"CATEGORIA" : "RES CONSERV HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 36,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 29,
		"PORCENTAJE_OCUPACION" : 83.72
	},
	{
		"CATEGORIA" : "N14 PROMO BRIG SAL COM 80",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 6,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 72.73
	},
	{
		"CATEGORIA" : "COORD PROGS NO MED RURAL E0",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 58.33
	},
	{
		"CATEGORIA" : "N39 ANALISTA RESP B    80",
		"PLAZAS_OCUPADAS" : 26,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 21,
		"PORCENTAJE_OCUPACION" : 83.87
	},
	{
		"CATEGORIA" : "MED GENERAL UNIDAD MEDICA E0",
		"PLAZAS_OCUPADAS" : 21,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 80.77
	},
	{
		"CATEGORIA" : "RESPONSABLE SISTEMAS HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 25,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 20,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "ANALISTA SUPERVISOR E1",
		"PLAZAS_OCUPADAS" : 24,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 19,
		"PORCENTAJE_OCUPACION" : 82.76
	},
	{
		"CATEGORIA" : "SUPERV PROYECTOS E3",
		"PLAZAS_OCUPADAS" : 22,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 81.48
	},
	{
		"CATEGORIA" : "JEFE DIV OPERATIVA E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : -4,
		"PORCENTAJE_OCUPACION" : 16.67
	},
	{
		"CATEGORIA" : "N43 MEDICO ESP HR 80",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 11,
		"PORCENTAJE_OCUPACION" : 78.95
	},
	{
		"CATEGORIA" : "SUPERV ADMON ARCH CLIN RURAL E0",
		"PLAZAS_OCUPADAS" : 23,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 19,
		"PORCENTAJE_OCUPACION" : 85.19
	},
	{
		"CATEGORIA" : "N50 SUPERV PROG ENF RURAL 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "SUPERV PROYECTOS E2",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 70.00
	},
	{
		"CATEGORIA" : "N38 ANALISTA RESP C    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 25.00
	},
	{
		"CATEGORIA" : "N43 ANALISTA COORD B   80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "JEFE ENF HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "N41 ANALISTA COORD C   80",
		"PLAZAS_OCUPADAS" : 11,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 78.57
	},
	{
		"CATEGORIA" : "SUPERV PROYECTOS E1",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -3,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "RESP PROYECTOS E3",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -3,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "ANALISTA E3",
		"PLAZAS_OCUPADAS" : 25,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 22,
		"PORCENTAJE_OCUPACION" : 89.29
	},
	{
		"CATEGORIA" : "N57 COORD PROG NO MED RURAL 80",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 88.89
	},
	{
		"CATEGORIA" : "N25 SRIA AUXILIAR      80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "N27 ANALISTA D         80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N41 COORD CURSOS TEC   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "SUPERV ENFERMERIA RURAL E0",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 71.43
	},
	{
		"CATEGORIA" : "SUPERV MEDICO PROGS RURAL E0",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 80.00
	},
	{
		"CATEGORIA" : "TECNICO POLIVALENTE    80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N25 ASISTENTE ADMVO A  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "JEFE AREA NIVEL CENTRAL E0",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 60.00
	},
	{
		"CATEGORIA" : "N63 JEFE DIVISION B    80",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 80.00
	},
	{
		"CATEGORIA" : "N41 SRIA B COORD GRAL  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "N30 CHOFER COORD GRAL  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "SECRETARIA E6",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "MED ESPECIAL HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 60.00
	},
	{
		"CATEGORIA" : "N47 LIDER PROYECTO C   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "N36 ANALISTA RESP D    80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N33 ANALISTA A         80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N62 JEFE AREA MED RURAL 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N39 RESPONSABLE SISTEMAS HOSPITAL RURAL",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "AUX TECNICO E2",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N31 SRIA AUX JEFE AREA 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "COORD PROYECTO E2",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "JEFE AREA MEDICA RURAL E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "LAB HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 80.00
	},
	{
		"CATEGORIA" : "N62 JEFE AREA MEDICA   80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "SUPERV CONSERVACION RURAL E0",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "COORD PROGS NIVEL CENTRAL E1",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "AUX ADMVO E2",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "DIR HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 94.44
	},
	{
		"CATEGORIA" : "N14 AYTE ADMVO         80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N56 ASESOR COORDINADOR 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "SECRETARIA E7",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "SUPERV ACCION COMUNIT RURAL E0",
		"PLAZAS_OCUPADAS" : 12,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 11,
		"PORCENTAJE_OCUPACION" : 92.31
	},
	{
		"CATEGORIA" : "N43 SRIA A COORD       80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "ENFERM GRAL HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 64,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 63,
		"PORCENTAJE_OCUPACION" : 98.46
	},
	{
		"CATEGORIA" : "AUX ADMVO E3",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N37 SRIA JEF DEP ADVO A80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N49 JEFE OFNA DELEG 3  80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N57 COORD PROG EST RURAL 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N60 COORD TECNICO A    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "COORD TEC NIVEL CENTRAL E2",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N47 JEFE OFNA DELEG 2  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N57 COORD PROG MED RURAL 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "N39 SRIA B COORD       80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "DIETISTA HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N35 SRIA JEFE DE AREA  80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N57 COOR DELEG MED RURAL 80",
		"PLAZAS_OCUPADAS" : 9,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 90.00
	},
	{
		"CATEGORIA" : "DENTISTA HOSPITAL RURAL E0",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "RESIDENTE CONSTRUCCIONES E3",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PAS ENFERMERIA B SS    80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TERAPISTA FISICO       80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ABOGADO PROCURADOR E0",
		"PLAZAS_OCUPADAS" : 18,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N10 AUX ADMVO RURAL 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "SECRETARIA E4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESIDENTE CONSTRUCCIONES E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PAS C MEDICINA SER SOC 80",
		"PLAZAS_OCUPADAS" : 969,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 969,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N20 DIETISTA HR 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ENF GRAL CLINICA UNIDAD PROG 80",
		"PLAZAS_OCUPADAS" : 23,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 23,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "SUPERV INSTALS CONSTRUCCIONES E2",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N57 COORD PROGRAMAS    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N43 ANESTESIOLOGO UMH  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N63 JEFE DEPTO ADMVO A 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PAS ENFERMERIA C SS    80",
		"PLAZAS_OCUPADAS" : 172,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 172,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUXILIAR DE ALMACEN    80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "SECRETARIA E11",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N50 LIDER PROYECTO A   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N40 ANALISTA RESP A    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PAS ODONTOLOGIA C SS   80",
		"PLAZAS_OCUPADAS" : 22,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 22,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 RESPONSABLE PROY C 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX ADMVO RURAL E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N62 JEFE DE AREA ENF 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N17 ASISTENTE ADMVO C  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "CHOFER                 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N34 MEDICO GRAL U MED  80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N22 ASISTENTE ADMVO B  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OP DE SERVS AUXS UMC L 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N18 TECNICO OFFSET     80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N62 JEFE DE AREA       80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ASISTENTE INFORMACION E2",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N26 PSICOLOGO H R 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N47 SRIA B DIRECTOR    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OF DE SERVS ADMVOS     80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N50 COORD PROG TS MED RURAL",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PAS ENFERMER CC SOC 80",
		"PLAZAS_OCUPADAS" : 171,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 171,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ANALISTA E1",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX UNIV DE OFICINAS   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD DELEG MED RURAL E0",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 ANALISTA COORD A   80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N47 RESID B PROY CONST 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ANALISTA SUPERVISOR E2",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OFICIAL DE PERSONAL    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD PROGS EST RURAL E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD PROYECTO E1",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 ABOGADO PROCURADOR 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	}
];
