/* query para crear la tabla plazas ocupadas y vacantes por OOAD ejecutar el siguiente query
SELECT
	p.NUMDEL,
	p.DELEGACION,
	COUNT(DISTINCT p.DEPENDENCIA) AS TOTAL_UNIDADES,
	SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) AS OCUPADAS,
	SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) AS VACANTES,
	ROUND(SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) * 100.0 / 
		NULLIF(SUM(CASE WHEN p.PLZOCU = 1 OR p.PLZVAC = 1 THEN 1 ELSE 0 END), 0), 2) AS PORCENTAJE_OCUPADAS,
	ROUND(SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) * 100.0 / 
		NULLIF(SUM(CASE WHEN p.PLZOCU = 1 OR p.PLZVAC = 1 THEN 1 ELSE 0 END), 0), 2) AS PORCENTAJE_VACANTES
FROM 
	personalaps.plantillaordinario p
WHERE 
	DESCRIP_CLASCATEG = '1.MÉDICOS'
AND QNA = '2024017'
GROUP BY
	p.NUMDEL, p.DELEGACION
ORDER BY
	p.NUMDEL; */

const datosDelegaciones = [
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"TOTAL_UNIDADES" : 15,
		"OCUPADAS" : 236,
		"VACANTES" : 31,
		"PORCENTAJE_OCUPADAS" : 88.39,
		"PORCENTAJE_VACANTES" : 11.61
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"TOTAL_UNIDADES" : 47,
		"OCUPADAS" : 368,
		"VACANTES" : 56,
		"PORCENTAJE_OCUPADAS" : 86.79,
		"PORCENTAJE_VACANTES" : 13.21
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"TOTAL_UNIDADES" : 88,
		"OCUPADAS" : 587,
		"VACANTES" : 104,
		"PORCENTAJE_OCUPADAS" : 84.95,
		"PORCENTAJE_VACANTES" : 15.05
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"TOTAL_UNIDADES" : 3,
		"OCUPADAS" : 106,
		"VACANTES" : 19,
		"PORCENTAJE_OCUPADAS" : 84.80,
		"PORCENTAJE_VACANTES" : 15.20
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"TOTAL_UNIDADES" : 621,
		"OCUPADAS" : 2500,
		"VACANTES" : 567,
		"PORCENTAJE_OCUPADAS" : 81.51,
		"PORCENTAJE_VACANTES" : 18.49
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"TOTAL_UNIDADES" : 163,
		"OCUPADAS" : 576,
		"VACANTES" : 218,
		"PORCENTAJE_OCUPADAS" : 72.54,
		"PORCENTAJE_VACANTES" : 27.46
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"TOTAL_UNIDADES" : 1,
		"OCUPADAS" : 212,
		"VACANTES" : 209,
		"PORCENTAJE_OCUPADAS" : 50.36,
		"PORCENTAJE_VACANTES" : 49.64
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"TOTAL_UNIDADES" : 181,
		"OCUPADAS" : 615,
		"VACANTES" : 229,
		"PORCENTAJE_OCUPADAS" : 72.87,
		"PORCENTAJE_VACANTES" : 27.13
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"TOTAL_UNIDADES" : 28,
		"OCUPADAS" : 200,
		"VACANTES" : 43,
		"PORCENTAJE_OCUPADAS" : 82.30,
		"PORCENTAJE_VACANTES" : 17.70
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"TOTAL_UNIDADES" : 235,
		"OCUPADAS" : 1133,
		"VACANTES" : 163,
		"PORCENTAJE_OCUPADAS" : 87.42,
		"PORCENTAJE_VACANTES" : 12.58
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"TOTAL_UNIDADES" : 35,
		"OCUPADAS" : 331,
		"VACANTES" : 71,
		"PORCENTAJE_OCUPADAS" : 82.34,
		"PORCENTAJE_VACANTES" : 17.66
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"TOTAL_UNIDADES" : 369,
		"OCUPADAS" : 1381,
		"VACANTES" : 303,
		"PORCENTAJE_OCUPADAS" : 82.01,
		"PORCENTAJE_VACANTES" : 17.99
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"TOTAL_UNIDADES" : 235,
		"OCUPADAS" : 908,
		"VACANTES" : 64,
		"PORCENTAJE_OCUPADAS" : 93.42,
		"PORCENTAJE_VACANTES" : 6.58
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"TOTAL_UNIDADES" : 531,
		"OCUPADAS" : 2594,
		"VACANTES" : 310,
		"PORCENTAJE_OCUPADAS" : 89.33,
		"PORCENTAJE_VACANTES" : 10.67
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"TOTAL_UNIDADES" : 341,
		"OCUPADAS" : 1517,
		"VACANTES" : 357,
		"PORCENTAJE_OCUPADAS" : 80.95,
		"PORCENTAJE_VACANTES" : 19.05
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"TOTAL_UNIDADES" : 235,
		"OCUPADAS" : 1157,
		"VACANTES" : 379,
		"PORCENTAJE_OCUPADAS" : 75.33,
		"PORCENTAJE_VACANTES" : 24.67
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"TOTAL_UNIDADES" : 114,
		"OCUPADAS" : 528,
		"VACANTES" : 98,
		"PORCENTAJE_OCUPADAS" : 84.35,
		"PORCENTAJE_VACANTES" : 15.65
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"TOTAL_UNIDADES" : 114,
		"OCUPADAS" : 572,
		"VACANTES" : 152,
		"PORCENTAJE_OCUPADAS" : 79.01,
		"PORCENTAJE_VACANTES" : 20.99
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"TOTAL_UNIDADES" : 188,
		"OCUPADAS" : 900,
		"VACANTES" : 8,
		"PORCENTAJE_OCUPADAS" : 99.12,
		"PORCENTAJE_VACANTES" : 0.88
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"TOTAL_UNIDADES" : 316,
		"OCUPADAS" : 1032,
		"VACANTES" : 213,
		"PORCENTAJE_OCUPADAS" : 82.89,
		"PORCENTAJE_VACANTES" : 17.11
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"TOTAL_UNIDADES" : 253,
		"OCUPADAS" : 879,
		"VACANTES" : 218,
		"PORCENTAJE_OCUPADAS" : 80.13,
		"PORCENTAJE_VACANTES" : 19.87
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"TOTAL_UNIDADES" : 96,
		"OCUPADAS" : 786,
		"VACANTES" : 101,
		"PORCENTAJE_OCUPADAS" : 88.61,
		"PORCENTAJE_VACANTES" : 11.39
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"TOTAL_UNIDADES" : 157,
		"OCUPADAS" : 1148,
		"VACANTES" : 276,
		"PORCENTAJE_OCUPADAS" : 80.62,
		"PORCENTAJE_VACANTES" : 19.38
	}
];

/* query para extraer esta información del modal desagregado
SELECT 
    p.NUMDEL, 
    p.DELEGACION, 
    p.CATEGORIA AS CATEGORIA, 
    p.DESCRIP_CLASCATEG AS DESCRIPCION,
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) AS VACANTES
FROM 
    personalaps.plantillaordinario p
WHERE p.DESCRIP_CLASCATEG = "1.MÉDICOS"
AND QNA = '2024017'
GROUP BY 
    p.NUMDEL, p.DELEGACION, p.CATEGORIA
HAVING 
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) > 0
ORDER BY 
    p.NUMDEL, p.CATEGORIA;
*/
const datosDelegacionesDesagregado = [
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 19
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N43 MEDICO ESP HR 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "RESPONSABLE SISTEMAS HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "SUPERV ADMON ARCH CLIN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "ADMINISTRADOR HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "JEFE ENF HOSPITAL RURAL E0",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 31
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N41 JEFE ENF HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N46 SUPERVISOR ENF RURAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "NUTRICIONISTA DIET HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "RES CONSERV HOSPITAL RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 17
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 45
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "PSICOLOGO HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "RES CONSERV HOSPITAL RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "NUTRICIONISTA DIET HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "ADMINISTRADOR HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "ANALISTA SISTEMAS RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "AUX ALMACEN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 33
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 70
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 37
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "CHOFER RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "CITOTECNOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "ENFERM GRAL HOSPITAL RURAL E0",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 125
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 149
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N14 PROMO BRIG SAL COM 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N26 TEC RURAL SALUD 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N39 ANALISTA RESP B    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N39 RESPONSABLE SISTEMAS HOSPITAL RURAL",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N41 RESIDENTE CONS HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N56 SUPERV MED PROG RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "PSICOLOGO HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "RESPONSABLE SISTEMAS HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "SUPERV ACCION COMUNIT RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "SUPERV CONSERVACION RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "TRABAJADORA SOCIAL HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 63
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "JEFE ENF HOSPITAL RURAL E0",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 59
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 55
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N46 SUPERVISOR ENF RURAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "TRABAJADORA SOCIAL HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "ANALISTA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 15
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "ANALISTA E3",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "ANALISTA SISTEMAS RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "ANALISTA SUPERVISOR E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "AUX ADMVO E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "AUX ADMVO E3",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "AUX TECNICO E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "COORD PROGS NIVEL CENTRAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "COORD PROGS NO MED RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "COORD PROYECTO E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "COORD TEC NIVEL CENTRAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "DIETISTA HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "JEFE AREA MEDICA RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "JEFE AREA NIVEL CENTRAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "JEFE DIV OPERATIVA E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "MED ESPECIAL HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "MED GENERAL UNIDAD MEDICA E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N14 AYTE ADMVO         80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N14 PROMO BRIG SAL COM 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N25 ASISTENTE ADMVO A  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N25 SRIA AUXILIAR      80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N26 ANALISTA SISTEMAS RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N26 TEC RURAL SALUD 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N27 ANALISTA D         80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N30 CHOFER COORD GRAL  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 17
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N31 SRIA AUX JEFE AREA 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N33 ANALISTA A         80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N35 SRIA JEFE DE AREA  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N36 ANALISTA RESP D    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N37 SRIA JEF DEP ADVO A80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N38 ANALISTA RESP C    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N39 SRIA B COORD       80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N41 ANALISTA COORD C   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N41 COORD CURSOS TEC   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N41 SRIA B COORD GRAL  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N43 ANALISTA COORD B   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N43 SRIA A COORD       80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N46 SUPERVISOR ENF RURAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N47 LIDER PROYECTO C   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N49 LIDER PROYECTO B   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N50 SUPERV PROG ENF RURAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N53 RESPONSABLE PROY A 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N56 ASESOR COORDINADOR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N56 SUPERV MED PROG RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N57 COORD PROG EST RURAL 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N57 COORD PROG MED RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N57 COORD PROG NO MED RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N60 COORD TECNICO A    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N62 JEFE AREA MED RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N62 JEFE AREA MEDICA   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N63 JEFE DIVISION B    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 15
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "RESP PROYECTOS E3",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "RESPONSABLE SISTEMAS HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "SECRETARIA E6",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "SECRETARIA E7",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "SUPERV ADMON ARCH CLIN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "SUPERV PROYECTOS E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "SUPERV PROYECTOS E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "SUPERV PROYECTOS E3",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "ADMINISTRADOR HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "AUX ALMACEN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 66
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "CHOFER RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 36
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 54
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N41 JEFE ENF HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N41 RESIDENTE CONS HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N56 SUPERV MED PROG RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "TRABAJADORA SOCIAL HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 15
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N36 ANALISTA RESP D    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N39 ANALISTA RESP B    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N41 RESIDENTE CONS HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "SUPERV MEDICO PROGS RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "ADMINISTRADOR HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 10
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "CHOFER RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 40
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 54
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N26 ANALISTA SISTEMAS RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N41 RESIDENTE CONS HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N56 SUPERV MED PROG RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "ANALISTA SISTEMAS RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 34
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "NUTRICIONISTA DIET HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "AUX ALMACEN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 53
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "DENTISTA HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 40
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 125
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N26 ANALISTA SISTEMAS RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N41 JEFE ENF HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N46 SUPERVISOR ENF RURAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N47 JEFE OFNA DELEG 2  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N56 SUPERV MED PROG RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "PSICOLOGO HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "RESPONSABLE SISTEMAS HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "TRABAJADORA SOCIAL HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "AUX ALMACEN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "CITOTECNOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 27
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N49 LIDER PROYECTO B   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "NUTRICIONISTA DIET HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "ADMINISTRADOR HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "ANALISTA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "ANALISTA SISTEMAS RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "AUX ALMACEN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 15
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "CHOFER RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "CITOTECNOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 36
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 97
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N41 JEFE ENF HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N41 RESIDENTE CONS HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N46 SUPERVISOR ENF RURAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N56 SUPERV MED PROG RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "PSICOLOGO HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "RES CONSERV HOSPITAL RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "SUPERV ENFERMERIA RURAL E0",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "SUPERV MEDICO PROGS RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "TRABAJADORA SOCIAL HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 12
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 135
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "JEFE ENF HOSPITAL RURAL E0",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 51
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 91
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N41 JEFE ENF HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "RES CONSERV HOSPITAL RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "RESPONSABLE SISTEMAS HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "TRABAJADORA SOCIAL HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "ANALISTA E3",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "AUX ALMACEN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 10
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 79
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "CHOFER RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "CITOTECNOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "LAB HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "MED GENERAL UNIDAD MEDICA E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 76
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 121
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N26 ANALISTA SISTEMAS RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N41 JEFE ENF HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N41 RESIDENTE CONS HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N43 MEDICO ESP HR 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N46 SUPERVISOR ENF RURAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N56 SUPERV MED PROG RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "NUTRICIONISTA DIET HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "PSICOLOGO HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "RES CONSERV HOSPITAL RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "SUPERV ADMON ARCH CLIN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "TECNICO POLIVALENTE    80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "TRABAJADORA SOCIAL HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ANALISTA SISTEMAS RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "CITOTECNOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 51
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 27
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 RESIDENTE CONS HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "AUX ALMACEN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "CHOFER RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 35
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 87
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N26 ANALISTA SISTEMAS RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N26 TEC RURAL SALUD 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "ADMINISTRADOR HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 46
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "CHOFER RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 69
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 52
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N41 SUPERV MED AUX UMR RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N46 SUPERVISOR ENF RURAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "NUTRICIONISTA DIET HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "PSICOLOGO HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "SUPERV ADMON ARCH CLIN RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "ADMINISTRADOR HOSPITAL RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "AUX AREA MEDICA UMC    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 19
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 122
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 32
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N12 CHOFER RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N14 AUX ALMACEN RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N22 AYTE ADMVO RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N41 JEFE ENF HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N52 DIRECTOR HOSP RURAL80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "SUPERV MEDICO AUX UMR RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "ANALISTA SISTEMAS RURAL E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 20
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "CHOFER POLIVALENTE RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 39
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N14 PROMO BRIG SAL COM 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N39 ANALISTA RESP B    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N45 COORD MEDICO HR",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N49 JEFE OFNA DELEG 3  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N57 COOR DELEG MED RURAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "AUX DE ADMON HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL HR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 13
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "AUX ENF GENERAL UMR",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 33
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "AUX SERVS GRALES HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "AYUD ADMVO RURAL E1",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "AYUD ADMVO RURAL E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "CITOTECNOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "COORD MEDICO HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "DIR HOSPITAL RURAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "ENFERMERA GENERAL HR 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "ESTOMATOLOGO HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "LABORATORISTA HR 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 88
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 87
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N14 AYTE ADMVO B RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N16 CHOFER POLIV RURAL 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N30 PROM ACCION COMUN RURAL  80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N39 ANALISTA RESP B    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N41 ADMINISTRADOR HR 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N46 SUPERV ACCION COM RURAL 80",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N46 SUPERVISOR ADM AC RURAL 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "OP DE MANTENIMIENTO HR 80",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "OP DE SERVS AUXS HR L 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "OP DE SERVS AUXS HR R 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "PROM ACCION COMUNITARIA RURAL E0",
		"DESCRIPCION" : "7.ACCIÓN COMUNITARIA",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "PSICOLOGO HOSPITAL RURAL E0",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "RES CONSERV HOSPITAL RURAL E0",
		"DESCRIPCION" : "8.SERVICIOS GENERALES",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "SECRETARIA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	}
];