/* query para extraer la informacion por rangos de edad
SELECT
    CASE 
	    WHEN p.EDAD BETWEEN 15 AND 19 THEN '15-19 años'
        WHEN p.EDAD BETWEEN 20 AND 29 THEN '20-29 años'
        WHEN p.EDAD BETWEEN 30 AND 39 THEN '30-39 años'
        WHEN p.EDAD BETWEEN 40 AND 49 THEN '40-49 años'
		WHEN p.EDAD BETWEEN 50 AND 59 THEN '50-59 años'
        WHEN p.EDAD BETWEEN 60 AND 69 THEN '60-69 años'
        WHEN p.EDAD >= 70 THEN '70+ años'
        ELSE 'Desconocido'
    END AS Rango_Edad,

    COUNT(*) AS Total_Medicos,
    SUM(CASE WHEN p.SEXO = 'H' THEN 1 ELSE 0 END) AS Hombres,
    SUM(CASE WHEN p.SEXO = 'M' THEN 1 ELSE 0 END) AS Mujeres,

    -- Estados
    SUM(CASE WHEN p.NUMDEL = 1 THEN 1 ELSE 0 END) AS Aguascalientes,
    SUM(CASE WHEN p.NUMDEL = 2 THEN 1 ELSE 0 END) AS Baja_California,
    SUM(CASE WHEN p.NUMDEL = 3 THEN 1 ELSE 0 END) AS Baja_California_Sur,
    SUM(CASE WHEN p.NUMDEL = 4 THEN 1 ELSE 0 END) AS Campeche,
    SUM(CASE WHEN p.NUMDEL = 5 THEN 1 ELSE 0 END) AS Coahuila,
    SUM(CASE WHEN p.NUMDEL = 6 THEN 1 ELSE 0 END) AS Colima,
    SUM(CASE WHEN p.NUMDEL = 7 THEN 1 ELSE 0 END) AS Chiapas,
    SUM(CASE WHEN p.NUMDEL = 8 THEN 1 ELSE 0 END) AS Chihuahua,
    SUM(CASE WHEN p.NUMDEL = 9 THEN 1 ELSE 0 END) AS Nivel_Central,
    SUM(CASE WHEN p.NUMDEL = 10 THEN 1 ELSE 0 END) AS Durango,
    SUM(CASE WHEN p.NUMDEL = 11 THEN 1 ELSE 0 END) AS Guanajuato,
    SUM(CASE WHEN p.NUMDEL = 12 THEN 1 ELSE 0 END) AS Guerrero,
    SUM(CASE WHEN p.NUMDEL = 13 THEN 1 ELSE 0 END) AS Hidalgo,
    SUM(CASE WHEN p.NUMDEL = 14 THEN 1 ELSE 0 END) AS Jalisco,
    SUM(CASE WHEN p.NUMDEL = 15 THEN 1 ELSE 0 END) AS Mexico_Oriente,
    SUM(CASE WHEN p.NUMDEL = 16 THEN 1 ELSE 0 END) AS Mexico_Poniente,
    SUM(CASE WHEN p.NUMDEL = 17 THEN 1 ELSE 0 END) AS Michoacan,
    SUM(CASE WHEN p.NUMDEL = 18 THEN 1 ELSE 0 END) AS Morelos,
    SUM(CASE WHEN p.NUMDEL = 19 THEN 1 ELSE 0 END) AS Nayarit,
    SUM(CASE WHEN p.NUMDEL = 20 THEN 1 ELSE 0 END) AS Nuevo_Leon,
    SUM(CASE WHEN p.NUMDEL = 21 THEN 1 ELSE 0 END) AS Oaxaca,
    SUM(CASE WHEN p.NUMDEL = 22 THEN 1 ELSE 0 END) AS Puebla,
    SUM(CASE WHEN p.NUMDEL = 23 THEN 1 ELSE 0 END) AS Queretaro,
    SUM(CASE WHEN p.NUMDEL = 24 THEN 1 ELSE 0 END) AS Quintana_Roo,
    SUM(CASE WHEN p.NUMDEL = 25 THEN 1 ELSE 0 END) AS San_Luis_Potosi,
    SUM(CASE WHEN p.NUMDEL = 26 THEN 1 ELSE 0 END) AS Sinaloa,
    SUM(CASE WHEN p.NUMDEL = 27 THEN 1 ELSE 0 END) AS Sonora,
    SUM(CASE WHEN p.NUMDEL = 28 THEN 1 ELSE 0 END) AS Tabasco,
    SUM(CASE WHEN p.NUMDEL = 29 THEN 1 ELSE 0 END) AS Tamaulipas,
    SUM(CASE WHEN p.NUMDEL = 30 THEN 1 ELSE 0 END) AS Tlaxcala,
    SUM(CASE WHEN p.NUMDEL = 31 THEN 1 ELSE 0 END) AS Veracruz_Norte,
    SUM(CASE WHEN p.NUMDEL = 32 THEN 1 ELSE 0 END) AS Veracruz_Sur,
    SUM(CASE WHEN p.NUMDEL = 33 THEN 1 ELSE 0 END) AS Yucatan,
    SUM(CASE WHEN p.NUMDEL = 34 THEN 1 ELSE 0 END) AS Zacatecas,
    SUM(CASE WHEN p.NUMDEL IN (35, 36) THEN 1 ELSE 0 END) AS DF_Norte,
    SUM(CASE WHEN p.NUMDEL IN (37, 38) THEN 1 ELSE 0 END) AS DF_Sur

FROM personalaps.plantillaordinario p
WHERE p.PLZOCU = 1 -- Solo plazas ocupadas
AND p.DESCRIP_CLASCATEG = '1.MÉDICOS' -- Solo médicos
AND QNA = '2024017'
GROUP BY Rango_Edad
ORDER BY Rango_Edad ASC;
*/

const datosMedicos = [
	{
		"Rango_Edad" : "20-29 años",
		"Total_Medicos" : 841,
		"Hombres" : 353,
		"Mujeres" : 488,
		"Aguascalientes" : 12,
		"Baja_California" : 16,
		"Baja_California_Sur" : 17,
		"Campeche" : 7,
		"Coahuila" : 66,
		"Colima" : 24,
		"Chiapas" : 4,
		"Chihuahua" : 29,
		"Nivel_Central" : 2,
		"Durango" : 4,
		"Guanajuato" : 17,
		"Guerrero" : 6,
		"Hidalgo" : 10,
		"Jalisco" : 80,
		"Mexico_Oriente" : 44,
		"Mexico_Poniente" : 30,
		"Michoacan" : 15,
		"Morelos" : 8,
		"Nayarit" : 28,
		"Nuevo_Leon" : 63,
		"Oaxaca" : 7,
		"Puebla" : 4,
		"Queretaro" : 10,
		"Quintana_Roo" : 14,
		"San_Luis_Potosi" : 5,
		"Sinaloa" : 18,
		"Sonora" : 83,
		"Tabasco" : 8,
		"Tamaulipas" : 25,
		"Tlaxcala" : 0,
		"Veracruz_Norte" : 27,
		"Veracruz_Sur" : 23,
		"Yucatan" : 9,
		"Zacatecas" : 1,
		"DF_Norte" : 53,
		"DF_Sur" : 72
	},
	{
		"Rango_Edad" : "30-39 años",
		"Total_Medicos" : 32703,
		"Hombres" : 14976,
		"Mujeres" : 17727,
		"Aguascalientes" : 665,
		"Baja_California" : 999,
		"Baja_California_Sur" : 403,
		"Campeche" : 275,
		"Coahuila" : 1428,
		"Colima" : 378,
		"Chiapas" : 536,
		"Chihuahua" : 1229,
		"Nivel_Central" : 57,
		"Durango" : 436,
		"Guanajuato" : 1218,
		"Guerrero" : 349,
		"Hidalgo" : 624,
		"Jalisco" : 2430,
		"Mexico_Oriente" : 1672,
		"Mexico_Poniente" : 1155,
		"Michoacan" : 775,
		"Morelos" : 447,
		"Nayarit" : 676,
		"Nuevo_Leon" : 2206,
		"Oaxaca" : 334,
		"Puebla" : 732,
		"Queretaro" : 743,
		"Quintana_Roo" : 504,
		"San_Luis_Potosi" : 570,
		"Sinaloa" : 863,
		"Sonora" : 1570,
		"Tabasco" : 355,
		"Tamaulipas" : 1053,
		"Tlaxcala" : 159,
		"Veracruz_Norte" : 1095,
		"Veracruz_Sur" : 753,
		"Yucatan" : 643,
		"Zacatecas" : 354,
		"DF_Norte" : 2362,
		"DF_Sur" : 2655
	},
	{
		"Rango_Edad" : "40-49 años",
		"Total_Medicos" : 32397,
		"Hombres" : 16146,
		"Mujeres" : 16251,
		"Aguascalientes" : 560,
		"Baja_California" : 1087,
		"Baja_California_Sur" : 383,
		"Campeche" : 250,
		"Coahuila" : 1093,
		"Colima" : 302,
		"Chiapas" : 540,
		"Chihuahua" : 1147,
		"Nivel_Central" : 221,
		"Durango" : 553,
		"Guanajuato" : 1339,
		"Guerrero" : 502,
		"Hidalgo" : 520,
		"Jalisco" : 2695,
		"Mexico_Oriente" : 1964,
		"Mexico_Poniente" : 1335,
		"Michoacan" : 904,
		"Morelos" : 487,
		"Nayarit" : 347,
		"Nuevo_Leon" : 1941,
		"Oaxaca" : 525,
		"Puebla" : 1020,
		"Queretaro" : 668,
		"Quintana_Roo" : 497,
		"San_Luis_Potosi" : 632,
		"Sinaloa" : 964,
		"Sonora" : 1005,
		"Tabasco" : 357,
		"Tamaulipas" : 958,
		"Tlaxcala" : 306,
		"Veracruz_Norte" : 914,
		"Veracruz_Sur" : 593,
		"Yucatan" : 838,
		"Zacatecas" : 310,
		"DF_Norte" : 2155,
		"DF_Sur" : 2485
	},
	{
		"Rango_Edad" : "50-59 años",
		"Total_Medicos" : 14567,
		"Hombres" : 8054,
		"Mujeres" : 6513,
		"Aguascalientes" : 226,
		"Baja_California" : 564,
		"Baja_California_Sur" : 159,
		"Campeche" : 117,
		"Coahuila" : 465,
		"Colima" : 117,
		"Chiapas" : 213,
		"Chihuahua" : 497,
		"Nivel_Central" : 165,
		"Durango" : 244,
		"Guanajuato" : 636,
		"Guerrero" : 218,
		"Hidalgo" : 230,
		"Jalisco" : 1291,
		"Mexico_Oriente" : 905,
		"Mexico_Poniente" : 561,
		"Michoacan" : 371,
		"Morelos" : 246,
		"Nayarit" : 153,
		"Nuevo_Leon" : 771,
		"Oaxaca" : 167,
		"Puebla" : 572,
		"Queretaro" : 250,
		"Quintana_Roo" : 201,
		"San_Luis_Potosi" : 328,
		"Sinaloa" : 392,
		"Sonora" : 326,
		"Tabasco" : 201,
		"Tamaulipas" : 417,
		"Tlaxcala" : 162,
		"Veracruz_Norte" : 422,
		"Veracruz_Sur" : 288,
		"Yucatan" : 379,
		"Zacatecas" : 154,
		"DF_Norte" : 940,
		"DF_Sur" : 1219
	},
	{
		"Rango_Edad" : "60-69 años",
		"Total_Medicos" : 2329,
		"Hombres" : 1609,
		"Mujeres" : 720,
		"Aguascalientes" : 36,
		"Baja_California" : 71,
		"Baja_California_Sur" : 13,
		"Campeche" : 24,
		"Coahuila" : 45,
		"Colima" : 15,
		"Chiapas" : 33,
		"Chihuahua" : 61,
		"Nivel_Central" : 69,
		"Durango" : 22,
		"Guanajuato" : 69,
		"Guerrero" : 77,
		"Hidalgo" : 41,
		"Jalisco" : 144,
		"Mexico_Oriente" : 121,
		"Mexico_Poniente" : 110,
		"Michoacan" : 74,
		"Morelos" : 42,
		"Nayarit" : 19,
		"Nuevo_Leon" : 113,
		"Oaxaca" : 43,
		"Puebla" : 88,
		"Queretaro" : 35,
		"Quintana_Roo" : 24,
		"San_Luis_Potosi" : 38,
		"Sinaloa" : 60,
		"Sonora" : 61,
		"Tabasco" : 32,
		"Tamaulipas" : 61,
		"Tlaxcala" : 13,
		"Veracruz_Norte" : 77,
		"Veracruz_Sur" : 64,
		"Yucatan" : 37,
		"Zacatecas" : 25,
		"DF_Norte" : 211,
		"DF_Sur" : 261
	},
	{
		"Rango_Edad" : "70+ años",
		"Total_Medicos" : 93,
		"Hombres" : 69,
		"Mujeres" : 24,
		"Aguascalientes" : 2,
		"Baja_California" : 2,
		"Baja_California_Sur" : 0,
		"Campeche" : 0,
		"Coahuila" : 1,
		"Colima" : 0,
		"Chiapas" : 1,
		"Chihuahua" : 4,
		"Nivel_Central" : 12,
		"Durango" : 1,
		"Guanajuato" : 0,
		"Guerrero" : 2,
		"Hidalgo" : 0,
		"Jalisco" : 3,
		"Mexico_Oriente" : 2,
		"Mexico_Poniente" : 3,
		"Michoacan" : 3,
		"Morelos" : 2,
		"Nayarit" : 0,
		"Nuevo_Leon" : 0,
		"Oaxaca" : 1,
		"Puebla" : 3,
		"Queretaro" : 0,
		"Quintana_Roo" : 1,
		"San_Luis_Potosi" : 0,
		"Sinaloa" : 1,
		"Sonora" : 0,
		"Tabasco" : 0,
		"Tamaulipas" : 5,
		"Tlaxcala" : 0,
		"Veracruz_Norte" : 2,
		"Veracruz_Sur" : 2,
		"Yucatan" : 1,
		"Zacatecas" : 1,
		"DF_Norte" : 14,
		"DF_Sur" : 24
	}
];
