/* query para crear la tabla plazas ocupadas y vacantes por OOAD ejecutar el siguiente query
SELECT
	p.NUMDEL,
	p.DELEGACION,
	COUNT(DISTINCT p.DEPENDENCIA) AS TOTAL_UNIDADES,
	SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) AS OCUPADAS,
	SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) AS VACANTES,
	ROUND(SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) * 100.0 / 
		NULLIF(SUM(CASE WHEN p.PLZOCU = 1 OR p.PLZVAC = 1 THEN 1 ELSE 0 END), 0), 2) AS PORCENTAJE_OCUPADAS,
	ROUND(SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) * 100.0 / 
		NULLIF(SUM(CASE WHEN p.PLZOCU = 1 OR p.PLZVAC = 1 THEN 1 ELSE 0 END), 0), 2) AS PORCENTAJE_VACANTES
FROM 
	personalaps.plantillaordinario p
WHERE 
	DESCRIP_CLASCATEG = '1.MÉDICOS'
AND QNA = '2024017'
GROUP BY
	p.NUMDEL, p.DELEGACION
ORDER BY
	p.NUMDEL; */

const datosDelegaciones = [
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"TOTAL_UNIDADES" : 18,
		"OCUPADAS" : 1501,
		"VACANTES" : 42,
		"PORCENTAJE_OCUPADAS" : 97.28,
		"PORCENTAJE_VACANTES" : 2.72
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"TOTAL_UNIDADES" : 45,
		"OCUPADAS" : 2739,
		"VACANTES" : 160,
		"PORCENTAJE_OCUPADAS" : 94.48,
		"PORCENTAJE_VACANTES" : 5.52
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"TOTAL_UNIDADES" : 28,
		"OCUPADAS" : 975,
		"VACANTES" : 80,
		"PORCENTAJE_OCUPADAS" : 92.42,
		"PORCENTAJE_VACANTES" : 7.58
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"TOTAL_UNIDADES" : 16,
		"OCUPADAS" : 673,
		"VACANTES" : 50,
		"PORCENTAJE_OCUPADAS" : 93.08,
		"PORCENTAJE_VACANTES" : 6.92
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"TOTAL_UNIDADES" : 68,
		"OCUPADAS" : 3098,
		"VACANTES" : 349,
		"PORCENTAJE_OCUPADAS" : 89.88,
		"PORCENTAJE_VACANTES" : 10.12
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"TOTAL_UNIDADES" : 19,
		"OCUPADAS" : 836,
		"VACANTES" : 52,
		"PORCENTAJE_OCUPADAS" : 94.14,
		"PORCENTAJE_VACANTES" : 5.86
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"TOTAL_UNIDADES" : 44,
		"OCUPADAS" : 1327,
		"VACANTES" : 130,
		"PORCENTAJE_OCUPADAS" : 91.08,
		"PORCENTAJE_VACANTES" : 8.92
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"TOTAL_UNIDADES" : 73,
		"OCUPADAS" : 2967,
		"VACANTES" : 761,
		"PORCENTAJE_OCUPADAS" : 79.59,
		"PORCENTAJE_VACANTES" : 20.41
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"TOTAL_UNIDADES" : 26,
		"OCUPADAS" : 526,
		"VACANTES" : 31,
		"PORCENTAJE_OCUPADAS" : 94.43,
		"PORCENTAJE_VACANTES" : 5.57
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"TOTAL_UNIDADES" : 41,
		"OCUPADAS" : 1260,
		"VACANTES" : 62,
		"PORCENTAJE_OCUPADAS" : 95.31,
		"PORCENTAJE_VACANTES" : 4.69
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"TOTAL_UNIDADES" : 65,
		"OCUPADAS" : 3279,
		"VACANTES" : 146,
		"PORCENTAJE_OCUPADAS" : 95.74,
		"PORCENTAJE_VACANTES" : 4.26
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"TOTAL_UNIDADES" : 29,
		"OCUPADAS" : 1154,
		"VACANTES" : 115,
		"PORCENTAJE_OCUPADAS" : 90.94,
		"PORCENTAJE_VACANTES" : 9.06
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"TOTAL_UNIDADES" : 25,
		"OCUPADAS" : 1425,
		"VACANTES" : 136,
		"PORCENTAJE_OCUPADAS" : 91.29,
		"PORCENTAJE_VACANTES" : 8.71
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"TOTAL_UNIDADES" : 146,
		"OCUPADAS" : 6643,
		"VACANTES" : 420,
		"PORCENTAJE_OCUPADAS" : 94.05,
		"PORCENTAJE_VACANTES" : 5.95
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"TOTAL_UNIDADES" : 62,
		"OCUPADAS" : 4708,
		"VACANTES" : 464,
		"PORCENTAJE_OCUPADAS" : 91.03,
		"PORCENTAJE_VACANTES" : 8.97
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"TOTAL_UNIDADES" : 54,
		"OCUPADAS" : 3194,
		"VACANTES" : 287,
		"PORCENTAJE_OCUPADAS" : 91.76,
		"PORCENTAJE_VACANTES" : 8.24
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"TOTAL_UNIDADES" : 65,
		"OCUPADAS" : 2142,
		"VACANTES" : 343,
		"PORCENTAJE_OCUPADAS" : 86.20,
		"PORCENTAJE_VACANTES" : 13.80
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"TOTAL_UNIDADES" : 29,
		"OCUPADAS" : 1232,
		"VACANTES" : 92,
		"PORCENTAJE_OCUPADAS" : 93.05,
		"PORCENTAJE_VACANTES" : 6.95
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"TOTAL_UNIDADES" : 31,
		"OCUPADAS" : 1223,
		"VACANTES" : 85,
		"PORCENTAJE_OCUPADAS" : 93.50,
		"PORCENTAJE_VACANTES" : 6.50
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"TOTAL_UNIDADES" : 78,
		"OCUPADAS" : 5094,
		"VACANTES" : 213,
		"PORCENTAJE_OCUPADAS" : 95.99,
		"PORCENTAJE_VACANTES" : 4.01
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"TOTAL_UNIDADES" : 31,
		"OCUPADAS" : 1077,
		"VACANTES" : 46,
		"PORCENTAJE_OCUPADAS" : 95.90,
		"PORCENTAJE_VACANTES" : 4.10
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"TOTAL_UNIDADES" : 61,
		"OCUPADAS" : 2419,
		"VACANTES" : 282,
		"PORCENTAJE_OCUPADAS" : 89.56,
		"PORCENTAJE_VACANTES" : 10.44
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"TOTAL_UNIDADES" : 32,
		"OCUPADAS" : 1706,
		"VACANTES" : 44,
		"PORCENTAJE_OCUPADAS" : 97.49,
		"PORCENTAJE_VACANTES" : 2.51
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"TOTAL_UNIDADES" : 21,
		"OCUPADAS" : 1241,
		"VACANTES" : 108,
		"PORCENTAJE_OCUPADAS" : 91.99,
		"PORCENTAJE_VACANTES" : 8.01
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"TOTAL_UNIDADES" : 44,
		"OCUPADAS" : 1573,
		"VACANTES" : 147,
		"PORCENTAJE_OCUPADAS" : 91.45,
		"PORCENTAJE_VACANTES" : 8.55
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"TOTAL_UNIDADES" : 53,
		"OCUPADAS" : 2298,
		"VACANTES" : 115,
		"PORCENTAJE_OCUPADAS" : 95.23,
		"PORCENTAJE_VACANTES" : 4.77
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"TOTAL_UNIDADES" : 90,
		"OCUPADAS" : 3045,
		"VACANTES" : 395,
		"PORCENTAJE_OCUPADAS" : 88.52,
		"PORCENTAJE_VACANTES" : 11.48
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"TOTAL_UNIDADES" : 39,
		"OCUPADAS" : 953,
		"VACANTES" : 132,
		"PORCENTAJE_OCUPADAS" : 87.83,
		"PORCENTAJE_VACANTES" : 12.17
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"TOTAL_UNIDADES" : 63,
		"OCUPADAS" : 2519,
		"VACANTES" : 326,
		"PORCENTAJE_OCUPADAS" : 88.54,
		"PORCENTAJE_VACANTES" : 11.46
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"TOTAL_UNIDADES" : 19,
		"OCUPADAS" : 640,
		"VACANTES" : 19,
		"PORCENTAJE_OCUPADAS" : 97.12,
		"PORCENTAJE_VACANTES" : 2.88
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"TOTAL_UNIDADES" : 62,
		"OCUPADAS" : 2537,
		"VACANTES" : 320,
		"PORCENTAJE_OCUPADAS" : 88.80,
		"PORCENTAJE_VACANTES" : 11.20
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"TOTAL_UNIDADES" : 72,
		"OCUPADAS" : 1723,
		"VACANTES" : 169,
		"PORCENTAJE_OCUPADAS" : 91.07,
		"PORCENTAJE_VACANTES" : 8.93
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"TOTAL_UNIDADES" : 63,
		"OCUPADAS" : 1907,
		"VACANTES" : 81,
		"PORCENTAJE_OCUPADAS" : 95.93,
		"PORCENTAJE_VACANTES" : 4.07
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"TOTAL_UNIDADES" : 40,
		"OCUPADAS" : 845,
		"VACANTES" : 77,
		"PORCENTAJE_OCUPADAS" : 91.65,
		"PORCENTAJE_VACANTES" : 8.35
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"TOTAL_UNIDADES" : 42,
		"OCUPADAS" : 2344,
		"VACANTES" : 144,
		"PORCENTAJE_OCUPADAS" : 94.21,
		"PORCENTAJE_VACANTES" : 5.79
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"TOTAL_UNIDADES" : 41,
		"OCUPADAS" : 3391,
		"VACANTES" : 348,
		"PORCENTAJE_OCUPADAS" : 90.69,
		"PORCENTAJE_VACANTES" : 9.31
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"TOTAL_UNIDADES" : 59,
		"OCUPADAS" : 3533,
		"VACANTES" : 364,
		"PORCENTAJE_OCUPADAS" : 90.66,
		"PORCENTAJE_VACANTES" : 9.34
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"TOTAL_UNIDADES" : 32,
		"OCUPADAS" : 3183,
		"VACANTES" : 313,
		"PORCENTAJE_OCUPADAS" : 91.05,
		"PORCENTAJE_VACANTES" : 8.95
	}
];

/* query para extraer esta información del modal desagregado
SELECT 
    p.NUMDEL, 
    p.DELEGACION, 
    p.CATEGORIA AS CATEGORIA, 
    p.DESCRIP_CLASCATEG AS DESCRIPCION,
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) AS VACANTES
FROM 
    personalaps.plantillaordinario p
WHERE p.DESCRIP_CLASCATEG = "1.MÉDICOS"
GROUP BY 
    p.NUMDEL, p.DELEGACION, p.CATEGORIA
HAVING 
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) > 0
ORDER BY 
    p.NUMDEL, p.CATEGORIA;
*/
const datosDelegacionesDesagregado = [
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 19
	},
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"CATEGORIA" : "N55 COORD AUX ATN MED D1YD2 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "01",
		"DELEGACION" : "Aguascalientes",
		"CATEGORIA" : "N58 COORDINADOR(A) PREV ATN SAL D1 Y D2",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 124
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N51 DIRECTOR UMH E     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 10
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "02",
		"DELEGACION" : "Baja California",
		"CATEGORIA" : "N58 COORDINADOR(A) PLAN ENL INST D3 Y D4",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 10
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 45
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "N52 SUBDIR MEDICO UMF  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "03",
		"DELEGACION" : "Baja California Sur",
		"CATEGORIA" : "N53 DIRECTOR  UMF 2    80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 36
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "04",
		"DELEGACION" : "Campeche",
		"CATEGORIA" : "N55 COORD AUX MED SALUD TRAB D1YD2 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "MED TRAS PAC TERAP INT 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 12
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 23
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 17
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 250
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 17
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N53 COORD HOSP DON ORG Y TEJ UMAE",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N54 SUBDIR MED UMH B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N56 COORD AUX GEST MED D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N56 COORD AUX MED INVEST D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "05",
		"DELEGACION" : "Coahuila",
		"CATEGORIA" : "N58 COORDINADOR(A) PLAN ENL INST D3 Y D4",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 34
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "N51 JEFE DEPTO CLINICO 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "N52 INVEST ASOCIADO C  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "06",
		"DELEGACION" : "Colima",
		"CATEGORIA" : "N53 SUBDIR MED UMH C   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 68
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N51 COORD HOSP DON ORG Y TEJ UMH",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 15
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N53 COOR AUX PROG M D2 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N54 DIRECTOR UMF 1     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N54 MED SUP EPIDEMIOLOGO 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N54 MED SUP HOSPITALES 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N54 SUBDIR MED UMH B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N55 COORD AUX MED SPPSTIMSS D1YD2 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "07",
		"DELEGACION" : "Chiapas",
		"CATEGORIA" : "N55 DIRECTOR UMH B     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 31
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 27
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 646
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N51 COORD HOSP DON ORG Y TEJ UMH",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 36
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N53 SUBDIR MED UMH C   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "08",
		"DELEGACION" : "Chihuahua",
		"CATEGORIA" : "N58 COORDINADOR(A) SALUD TRAB D3 Y D4",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "JEFE AREA MEDICA NIVEL CENTRAL E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "JEFE UNIDAD INVEST MEDICA E0",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N49 INVEST ASOCIADO A  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N51 MEDICO ESP ST      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N52 INVEST ASOCIADO C  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N56 INVEST TITULAR B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N57 COORD PROG MED     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 13
	},
	{
		"NUMDEL" : "09",
		"DELEGACION" : "Nivel Central",
		"CATEGORIA" : "N62 JEFE AREA MEDICA   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 44
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N53 INVEST ASOCIADO D  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N54 DIRECTOR UMF 1     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N56 MED SUP LIDER 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "10",
		"DELEGACION" : "Durango",
		"CATEGORIA" : "N60 JEFE UNID INV MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 24
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 15
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 74
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N51 COORD HOSP DON ORG Y TEJ UMH",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 12
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "11",
		"DELEGACION" : "Guanajuato",
		"CATEGORIA" : "N56 COORD AUX MED INVEST D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 90
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N52 SUBD MED UM C      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N53 SUBDIR MED UMH C   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N54 DIRECTOR UMH C     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "12",
		"DELEGACION" : "Guerrero",
		"CATEGORIA" : "N55 COORD AUX MED SAL PUBLICA D1YD2 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 10
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 103
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N53 SUBDIR MED UMH C   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "13",
		"DELEGACION" : "Hidalgo",
		"CATEGORIA" : "N54 DIRECTOR UMH C     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "MED TRAS PAC TERAP INT 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 57
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 50
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 235
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N50 INVEST ASOCIADO B  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 19
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N52 INVEST ASOCIADO C  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N52 SUBD MED UM B      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N53 INVEST ASOC D MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N53 INVEST ASOCIADO D  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N53 JEF SPPSTIMSS UMAE 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N54 MED SUP HOSPITALES 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N55 INVEST TITULAR A   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N56 COORD AUX GEST MED D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N56 INVEST TITULAR B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N58 INVEST TITULAR C   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "14",
		"DELEGACION" : "Jalisco",
		"CATEGORIA" : "N60 JEFE UNIDAD INVEST 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "MED TRAS PAC TERAP INT 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 25
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 37
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 37
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 314
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "N51 COORD HOSP DON ORG Y TEJ UMH",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 24
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "N51 MEDICO ESP ST      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "15",
		"DELEGACION" : "México Oriente",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 10
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 97
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 39
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 124
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N54 MED SUP HOSPITALES 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "16",
		"DELEGACION" : "México Poniente",
		"CATEGORIA" : "N56 MED SUP LIDER 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 18
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 26
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 276
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N49 INVEST ASOCIADO A  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N51 COORD HOSP DON ORG Y TEJ UMH",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N54 DIRECTOR UMF 1     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "17",
		"DELEGACION" : "Michoacán",
		"CATEGORIA" : "N55 INVEST TITULAR A   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "INVESTIGADOR ASOCIADO E2",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 67
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N49 INVEST ASOCIADO A  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N50 INVEST ASOCIADO B  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 10
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N52 INVEST ASOCIADO C  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N52 SUBD MED UM C      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N55 INVEST TIT A MED   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "18",
		"DELEGACION" : "Morelos",
		"CATEGORIA" : "N56 INVEST TITULAR B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 59
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N52 SUBD MED UM C      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "19",
		"DELEGACION" : "Nayarit",
		"CATEGORIA" : "N55 DIRECTOR UMH B     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 138
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N49 INVEST ASOCIADO A  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N50 INVEST ASOCIADO B  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N52 INVEST ASOCIADO C  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N52 JEFE DIVISION UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N52 SUBDIR MEDICO UMF  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N53 DIRECTOR  UMF 2    80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N53 INVEST ASOCIADO D  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N55 INVEST TIT A MED   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N55 INVEST TITULAR A   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N56 COORD AUX MED SALUD TRAB D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N57 COOR CLIN TUR UMAE 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N58 COORDINADOR(A) INF AN EST D3 Y D4",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N58 DIR ED INV SA UMAE 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N60 DIR CENT INV B MED 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "20",
		"DELEGACION" : "Nuevo León",
		"CATEGORIA" : "N60 JEFE UNID INV MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 28
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "21",
		"DELEGACION" : "Oaxaca",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "MED TRAS PAC TERAP INT 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 30
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 18
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 194
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N52 JEFE DIVISION UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N56 INVEST TITULAR B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "22",
		"DELEGACION" : "Puebla",
		"CATEGORIA" : "N57 COOR CLIN TUR UMAE 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 25
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "23",
		"DELEGACION" : "Querétaro",
		"CATEGORIA" : "N53 SUBDIR MED UMH C   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 13
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 72
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "24",
		"DELEGACION" : "Quintana Roo",
		"CATEGORIA" : "N54 MED SUP HOSPITALES 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 27
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 18
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 78
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N54 SUBDIR MED UMH B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "25",
		"DELEGACION" : "San Luis Potosí",
		"CATEGORIA" : "N55 COORD AUX MED INVEST D1YD2 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 23
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 49
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 DIRECTOR UMH E     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 18
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N52 DIRECTOR UMF 3     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N53 DIRECTOR  UMF 2    80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "MED ESPECIALISTA PSIQUIATRA CAICE",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 32
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 17
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 291
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N48 DIRECTOR MICROZONA 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N51 MEDICO ESP ST      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N52 SUBDIR MEDICO UMF  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N53 SUBDIR MED UMH C   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N55 MED ESP PEDIATRA CAICE",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N56 COORD AUX GEST MED D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "27",
		"DELEGACION" : "Sonora",
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 106
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N51 COORD HOSP DON ORG Y TEJ UMH",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N52 SUBD MED UM C      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N53 DIRECTOR  UMF 2    80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "28",
		"DELEGACION" : "Tabasco",
		"CATEGORIA" : "N54 MED SUP HOSPITALES 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 291
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N51 MEDICO ESP ST      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N54 SUBDIR MED UMH B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N56 COORD AUX ATN MED D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "29",
		"DELEGACION" : "Tamaulipas",
		"CATEGORIA" : "N56 COORD AUX MED SAL PUBLICA D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "30",
		"DELEGACION" : "Tlaxcala",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 103
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 25
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 154
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N54 DIRECTOR UMF 1     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N54 DIRECTOR UMH C     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N54 MED SUP MED FAM 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N58 COORDINADOR(A) PLAN ENL INST D3 Y D4",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "31",
		"DELEGACION" : "Veracruz Norte",
		"CATEGORIA" : "N58 DIR ED INV SA UMAE 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 13
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 127
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N52 DIRECTOR UMF 3     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N52 JEFE CLIN SAL TRAB 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N54 MED SUP EPIDEMIOLOGO 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N54 SUBDIR MED UMH B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "32",
		"DELEGACION" : "Veracruz Sur",
		"CATEGORIA" : "N56 COORD AUX MED EDUCA D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 22
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 35
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N50 INVEST ASOCIADO B  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 8
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N51 MEDICO(A) RESP PROY CICR CANCER 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N51 PROFESOR(A) MEDICO(A) CESIECQ 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N52 DIRECTOR UMF 3     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N52 INVEST ASOC C MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N54 MED SUP EPIDEMIOLOGO 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "33",
		"DELEGACION" : "Yucatán",
		"CATEGORIA" : "N55 INVEST TITULAR A   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 15
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 36
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N53 SUBDIR MED UMH C   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N54 MED SUP MED FAM 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N54 SUBDIR MED UMH B   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "34",
		"DELEGACION" : "Zacatecas",
		"CATEGORIA" : "N58 COORDINADOR(A) PREV ATN SAL D1 Y D2",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 10
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 82
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 12
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N51 MEDICO ESP ST      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N52 JEFE DIVISION UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N52 SUBD MED UM C      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N52 SUBDIR MEDICO UMF  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N55 DIRECTOR UMH B     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "35",
		"DELEGACION" : "35 - DF Norte",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "MED TRAS PAC TERAP INT 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 27
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 27
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 226
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N43 MED ESP RAHB GERON CEAGE",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N49 JEF AREA MED CECART80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N51 DIRECTOR DE CECART 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 9
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N51 PROF MED CENT INV ED FORM DOC 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N53 INVEST ASOC D MED  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N53 INVEST ASOCIADO D  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N53 JEF SPPSTIMSS UMAE 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N55 INVEST TITULAR A   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N56 COORD AUX MED SALUD TRAB D3YD4 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "36",
		"DELEGACION" : "36 - DF Norte",
		"CATEGORIA" : "N56 MED SUP LIDER 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "MED TRAS PAC TERAP INT 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 53
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 21
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 224
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N49 INVEST ASOCIADO A  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N50 INVEST ASOCIADO B  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N51 MEDICO ESP ST      80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N51 PROF MED CENT INV ED FORM DOC 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N51 PROFESOR(A) MEDICO(A) CESIECQ 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N52 COOR AUX PROG M D1 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N52 JEFE DIVISION UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N52 SUBDIR MEDICO UMF  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 11
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N55 INVEST TIT A MED   80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "37",
		"DELEGACION" : "37 - DF Sur",
		"CATEGORIA" : "N58 DIR ED INV SA UMAE 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 22
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 75
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 13
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 178
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "N52 JEFE CLIN SAL TRAB 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "38",
		"DELEGACION" : "38 - DF Sur",
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	}
];