/*
SELECT 
    CASE 
        WHEN RJP = 'C108' THEN 'CUOTA SINDICAL'
        WHEN RJP = 'C111' THEN 'APORTACIÓN COMPLEMENTARIA AFORE'
        WHEN RJP = 'C152' THEN 'FONDO DE JUBILACIÓN'
        WHEN RJP = 'C152 Y C107' THEN 'FONDO DE JUBILACIÓN + NIVELACIÓN A PLAZA SUPERIOR'
        WHEN RJP = 'ESTATUTO' THEN 'ESTATUTO'
        WHEN RJP = 'SIN RJP' THEN 'SIN RÉGIMEN DE JUBILACIONES Y PENSIONES'
        ELSE RJP
    END AS RJP_DESCRIPCION,
    COUNT(*) AS cantidad
FROM personalaps.plantillaordinario
WHERE DESCRIP_CLASCATEG = "1.MÉDICOS" 
AND PLZOCU = 1
AND QNA = '2024017'
AND NUMDEL = '27'
AND DELEGACION = 'Sonora'
GROUP BY RJP_DESCRIPCION
ORDER BY cantidad DESC;
*/
var dona = [
	{
		"RJP_DESCRIPCION" : "APORTACIÓN COMPLEMENTARIA AFORE",
		"cantidad" : 2313
	},
	{
		"RJP_DESCRIPCION" : "FONDO DE JUBILACIÓN + NIVELACIÓN A PLAZA SUPERIOR",
		"cantidad" : 459
	},
	{
		"RJP_DESCRIPCION" : "CUOTA SINDICAL",
		"cantidad" : 270
	},
	{
		"RJP_DESCRIPCION" : "SIN RÉGIMEN DE JUBILACIONES Y PENSIONES",
		"cantidad" : 3
	}
];