/*Extraer este es un problema pero estos son los querys aplicados paso por paso para hacerlo

-- Numero 1

CREATE TABLE procesado.plazas_vacantes_por_estado_TOTAL AS
SELECT
    p.NUMDEL,
    CASE
        WHEN p.NUMDEL IN ('31', '32') THEN '30' -- Agrupa Veracruz Norte y Sur como 30
        WHEN p.NUMDEL IN ('35', '36', '37', '38') THEN '09' -- Agrupa Ciudad de México (DF Norte y Sur) como 09
        WHEN p.NUMDEL IN ('15', '16') THEN '15' -- Agrupa México Oriente y Poniente como 15
        ELSE p.NUMDEL -- Deja los demás estados igual
    END AS NUMELINEGI,
    p.DELEGACION,
    COUNT(DISTINCT p.DEPENDENCIA) AS TOTAL_UNIDADES,
    SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) AS OCUPADAS,
    SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) AS VACANTES
FROM
    personalaps.plantillaordinario p
WHERE DESCRIP_CLASCATEG = '1.MÉDICOS'
AND p.QNA = '2024017'
GROUP BY
    NUMELINEGI, p.NUMDEL, p.DELEGACION
ORDER BY
    NUMELINEGI, p.NUMDEL;

SELECT * FROM procesado.plazas_vacantes_por_estado_TOTAL;


-- Numero 2

UPDATE procesado.plazas_vacantes_por_estado_TOTAL
SET NUMELINEGI = 
    CASE 
        WHEN DELEGACION = 'Michoacán' THEN '16'
        WHEN DELEGACION = 'Morelos' THEN '17'
        WHEN DELEGACION = 'Nayarit' THEN '18'
        WHEN DELEGACION = 'Nuevo León' THEN '19'
        WHEN DELEGACION = 'Oaxaca' THEN '20'
        WHEN DELEGACION = 'Puebla' THEN '21'
        WHEN DELEGACION = 'Querétaro' THEN '22'
        WHEN DELEGACION = 'Quintana Roo' THEN '23'
        WHEN DELEGACION = 'San Luis Potosí' THEN '24'
        WHEN DELEGACION = 'Sinaloa' THEN '25'
        WHEN DELEGACION = 'Sonora' THEN '26'
        WHEN DELEGACION = 'Tabasco' THEN '27'
        WHEN DELEGACION = 'Tamaulipas' THEN '28'
        WHEN DELEGACION = 'Tlaxcala' THEN '29'
        WHEN DELEGACION = 'Veracruz Norte' THEN '30'
        WHEN DELEGACION = 'Veracruz Sur' THEN '30'
        WHEN DELEGACION = 'Yucatán' THEN '31'
        WHEN DELEGACION = 'Zacatecas' THEN '32'
        ELSE NUMELINEGI
    END
WHERE DELEGACION IN ('Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 
                     'Puebla', 'Querétaro', 'Quintana Roo', 'San Luis Potosí', 
                     'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 
                     'Veracruz Norte', 'Veracruz Sur', 'Yucatán', 'Zacatecas');


-- Numero 3

CREATE TABLE procesado.vacantes_estado_densidad_poblacional_TOTAL AS
SELECT
    CASE
        -- Agrupar Veracruz Norte y Sur bajo NUMELINEGI 30
        WHEN pvpe.NUMELINEGI = '30' THEN '30'
        -- Agrupar Ciudad de México (DF Norte y Sur) bajo NUMELINEGI 09
        WHEN pvpe.NUMELINEGI = '09' THEN '09'
        -- Agrupar México Oriente y Poniente bajo NUMELINEGI 15
        WHEN pvpe.NUMELINEGI = '15' THEN '15'
        ELSE pvpe.NUMELINEGI
    END AS NUMELINEGI,
    CASE
        -- Renombrar Veracruz agrupado
        WHEN pvpe.NUMELINEGI = '30' THEN 'Veracruz'
        -- Renombrar Ciudad de México agrupado
        WHEN pvpe.NUMELINEGI = '09' THEN 'Ciudad de México'
        -- Renombrar México agrupado
        WHEN pvpe.NUMELINEGI = '15' THEN 'Estado de México'
        ELSE pvpe.DELEGACION
    END AS DELEGACION,
    SUM(pvpe.TOTAL_UNIDADES) AS TOTAL_UNIDADES,
    SUM(pvpe.OCUPADAS) AS OCUPADAS,
    SUM(pvpe.VACANTES) AS VACANTES,
    SUM(catalogo.imss) AS DERECHOHABIENTES
FROM
    procesado.plazas_vacantes_por_estado_TOTAL pvpe
LEFT JOIN
    personalaps.catalogo_derechohabiencia_estado catalogo
    ON pvpe.NUMELINEGI = catalogo.numero_delegacion
GROUP BY
    NUMELINEGI, DELEGACION
ORDER BY
    NUMELINEGI;

SELECT *  FROM procesado.vacantes_estado_densidad_poblacional_TOTAL;


-- Numero 4

CREATE TABLE procesado.vacantes_estado_densidad_poblacional_agrupado_TOTAL AS
SELECT 
    NUMELINEGI,
    DELEGACION,
    SUM(TOTAL_UNIDADES) AS TOTAL_UNIDADES,
    SUM(VACANTES) AS PLAZAS_VACANTES,
    SUM(OCUPADAS) AS PLAZAS_OCUPADAS,
    MAX(DERECHOHABIENTES) AS DERECHOHABIENTES -- Obtiene cualquier valor (ya que son iguales)
FROM 
    procesado.vacantes_estado_densidad_poblacional_TOTAL
GROUP BY 
    NUMELINEGI, DELEGACION
ORDER BY 
    NUMELINEGI;

SELECT DELEGACION, DERECHOHABIENTES, PLAZAS_OCUPADAS, PLAZAS_VACANTES FROM procesado.vacantes_estado_densidad_poblacional_agrupado_TOTAL;

*/

// 📌 Array de datos SIN base de datos
const datos = [
	{
		"DELEGACION" : "Sinaloa",
		"DERECHOHABIENTES" : 1516933,
		"PLAZAS_OCUPADAS" : 11885,
		"PLAZAS_VACANTES" : 783
	}
];

/*
Query para extraer esta informacion de la tabla plazas ocupadas y vacantes por categoria 

SELECT 
    p.CATEGORIA,
    COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) AS PLAZAS_OCUPADAS,
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) AS PLAZAS_VACANTES,
    (COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) - 
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END)) AS DIFERENCIA,
    ROUND(
    COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) * 100.0 /
    NULLIF(COUNT(p.MATRICULA), 0), 2
) AS PORCENTAJE_OCUPACION
FROM 
    personalaps.plantillaordinario p
WHERE p.QNA = '2024017'
AND p.NUMDEL = '26'
AND p.DELEGACION = 'Sinaloa'
GROUP BY 
    p.CATEGORIA
ORDER BY 
    PLAZAS_VACANTES DESC;
*/

const datos8 = [
	{
		"CATEGORIA" : "ENFERMERA GENERAL CLINICA 80",
		"PLAZAS_OCUPADAS" : 553,
		"PLAZAS_VACANTES" : 137,
		"DIFERENCIA" : 416,
		"PORCENTAJE_OCUPACION" : 80.14
	},
	{
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"PLAZAS_OCUPADAS" : 1068,
		"PLAZAS_VACANTES" : 49,
		"DIFERENCIA" : 1019,
		"PORCENTAJE_OCUPACION" : 95.61
	},
	{
		"CATEGORIA" : "AUX UNIV DE OFICINAS   80",
		"PLAZAS_OCUPADAS" : 548,
		"PLAZAS_VACANTES" : 32,
		"DIFERENCIA" : 516,
		"PORCENTAJE_OCUPACION" : 94.48
	},
	{
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"PLAZAS_OCUPADAS" : 755,
		"PLAZAS_VACANTES" : 23,
		"DIFERENCIA" : 732,
		"PORCENTAJE_OCUPACION" : 97.04
	},
	{
		"CATEGORIA" : "OP GRAL EN TIENDAS     80",
		"PLAZAS_OCUPADAS" : 26,
		"PLAZAS_VACANTES" : 20,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 56.52
	},
	{
		"CATEGORIA" : "ENFERMERA GENERAL      80",
		"PLAZAS_OCUPADAS" : 909,
		"PLAZAS_VACANTES" : 18,
		"DIFERENCIA" : 891,
		"PORCENTAJE_OCUPACION" : 98.06
	},
	{
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"PLAZAS_OCUPADAS" : 70,
		"PLAZAS_VACANTES" : 18,
		"DIFERENCIA" : 52,
		"PORCENTAJE_OCUPACION" : 79.55
	},
	{
		"CATEGORIA" : "TECNICO POLIVALENTE    80",
		"PLAZAS_OCUPADAS" : 87,
		"PLAZAS_VACANTES" : 17,
		"DIFERENCIA" : 70,
		"PORCENTAJE_OCUPACION" : 83.65
	},
	{
		"CATEGORIA" : "ORIENT ACT FAMILIARES  20",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 17,
		"DIFERENCIA" : -13,
		"PORCENTAJE_OCUPACION" : 19.05
	},
	{
		"CATEGORIA" : "AUX LIMPIEZA E HIGIENE UM Y NO MED 80",
		"PLAZAS_OCUPADAS" : 507,
		"PLAZAS_VACANTES" : 16,
		"DIFERENCIA" : 491,
		"PORCENTAJE_OCUPACION" : 96.94
	},
	{
		"CATEGORIA" : "MEDICO GENERAL 80",
		"PLAZAS_OCUPADAS" : 241,
		"PLAZAS_VACANTES" : 16,
		"DIFERENCIA" : 225,
		"PORCENTAJE_OCUPACION" : 93.77
	},
	{
		"CATEGORIA" : "PREPARADOR DE MEZCLAS 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 15,
		"DIFERENCIA" : -15,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "AUX DE SERVS DE INT    80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 14,
		"DIFERENCIA" : -11,
		"PORCENTAJE_OCUPACION" : 17.65
	},
	{
		"CATEGORIA" : "OFICIAL PUERICULTURA   65",
		"PLAZAS_OCUPADAS" : 42,
		"PLAZAS_VACANTES" : 13,
		"DIFERENCIA" : 29,
		"PORCENTAJE_OCUPACION" : 76.36
	},
	{
		"CATEGORIA" : "ENFERMERA ESPECIALISTA 80",
		"PLAZAS_OCUPADAS" : 404,
		"PLAZAS_VACANTES" : 13,
		"DIFERENCIA" : 391,
		"PORCENTAJE_OCUPACION" : 96.88
	},
	{
		"CATEGORIA" : "AUXILIAR DE FARMACIA   80",
		"PLAZAS_OCUPADAS" : 91,
		"PLAZAS_VACANTES" : 13,
		"DIFERENCIA" : 78,
		"PORCENTAJE_OCUPACION" : 87.50
	},
	{
		"CATEGORIA" : "N12 OP  CAJAS TIENDA   80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 12,
		"DIFERENCIA" : -7,
		"PORCENTAJE_OCUPACION" : 29.41
	},
	{
		"CATEGORIA" : "OFICIAL DE ALMACEN     80",
		"PLAZAS_OCUPADAS" : 25,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 78.13
	},
	{
		"CATEGORIA" : "AUX DE TRAB SOCIAL     65",
		"PLAZAS_OCUPADAS" : 23,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 76.67
	},
	{
		"CATEGORIA" : "AUX DE SERVS DE INT    65",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : -6,
		"PORCENTAJE_OCUPACION" : 12.50
	},
	{
		"CATEGORIA" : "MANEJADOR ALIMENTOS    80",
		"PLAZAS_OCUPADAS" : 189,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 182,
		"PORCENTAJE_OCUPACION" : 96.43
	},
	{
		"CATEGORIA" : "AUXILIAR DE ALMACEN    80",
		"PLAZAS_OCUPADAS" : 55,
		"PLAZAS_VACANTES" : 6,
		"DIFERENCIA" : 49,
		"PORCENTAJE_OCUPACION" : 90.16
	},
	{
		"CATEGORIA" : "ASISTENTE MEDICA       80",
		"PLAZAS_OCUPADAS" : 248,
		"PLAZAS_VACANTES" : 6,
		"DIFERENCIA" : 242,
		"PORCENTAJE_OCUPACION" : 97.64
	},
	{
		"CATEGORIA" : "ORIENT INIC CULTURAL   20",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : -3,
		"PORCENTAJE_OCUPACION" : 28.57
	},
	{
		"CATEGORIA" : "MENSAJERO              65",
		"PLAZAS_OCUPADAS" : 19,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 79.17
	},
	{
		"CATEGORIA" : "TEC A AIRE ACON REFRIG 80",
		"PLAZAS_OCUPADAS" : 21,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 80.77
	},
	{
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL 80",
		"PLAZAS_OCUPADAS" : 1020,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 1015,
		"PORCENTAJE_OCUPACION" : 99.51
	},
	{
		"CATEGORIA" : "TEC A EQUIPOS MEDICOS  80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 72.22
	},
	{
		"CATEGORIA" : "N32 JEFE LIMP E HIG UMAE HGR HGZ 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : -5,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N41 SUBJ ENF UM A      80",
		"PLAZAS_OCUPADAS" : 32,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 27,
		"PORCENTAJE_OCUPACION" : 86.49
	},
	{
		"CATEGORIA" : "OPERADOR TELEFONICO A  65",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 44.44
	},
	{
		"CATEGORIA" : "ASISTENTE MEDICA       65",
		"PLAZAS_OCUPADAS" : 623,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 618,
		"PORCENTAJE_OCUPACION" : 99.20
	},
	{
		"CATEGORIA" : "N36 ANALISTA RESP D    80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 72.22
	},
	{
		"CATEGORIA" : "PROF EDUC FISICA A     40",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "OP SERVS DE LAVANDERIA 80",
		"PLAZAS_OCUPADAS" : 111,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 107,
		"PORCENTAJE_OCUPACION" : 96.52
	},
	{
		"CATEGORIA" : "ORIENT ACT FAMILIARES  40",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N39 SUPERVISOR LIMPIEZA E HIGIENE 80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 71.43
	},
	{
		"CATEGORIA" : "N24 SUBJ SER BAS UNI C 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : -4,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N44 RESP PROY D3       80",
		"PLAZAS_OCUPADAS" : 19,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 82.61
	},
	{
		"CATEGORIA" : "N39 ANALISTA RESP B    80",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "TECNICO PLOMERO        80",
		"PLAZAS_OCUPADAS" : 11,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 73.33
	},
	{
		"CATEGORIA" : "OFICIAL DE FARMACIA    80",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 13,
		"PORCENTAJE_OCUPACION" : 80.95
	},
	{
		"CATEGORIA" : "PROM SALUD COMUNITARIA 80",
		"PLAZAS_OCUPADAS" : 30,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 26,
		"PORCENTAJE_OCUPACION" : 88.24
	},
	{
		"CATEGORIA" : "N41 RES SAN FARM HOSP 2DO NIVEL TIPO B",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : -4,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "AYTE LIMPIEZA E HIGIENE UM Y NO MED 80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "AUX UNIV DE OFICINAS   65",
		"PLAZAS_OCUPADAS" : 90,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 87,
		"PORCENTAJE_OCUPACION" : 96.77
	},
	{
		"CATEGORIA" : "ABOGADO PROCURADOR E0",
		"PLAZAS_OCUPADAS" : 20,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 86.96
	},
	{
		"CATEGORIA" : "AUX ADMVO E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 25.00
	},
	{
		"CATEGORIA" : "N41 ANALISTA COORD C   80",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "NUTRICIONISTA DIETISTA 80",
		"PLAZAS_OCUPADAS" : 64,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 61,
		"PORCENTAJE_OCUPACION" : 95.52
	},
	{
		"CATEGORIA" : "N21 PROMOTOR(A) SAL INTEG PREVENIMSS 80",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 70.00
	},
	{
		"CATEGORIA" : "N30 ANALISTA C         80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 25.00
	},
	{
		"CATEGORIA" : "TRABAJADORA SOCIAL     65",
		"PLAZAS_OCUPADAS" : 54,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 51,
		"PORCENTAJE_OCUPACION" : 94.74
	},
	{
		"CATEGORIA" : "ORIENT ACT ARTISTICAS  33",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -3,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N36 RES SAN FARM HOSP 2DO NIVEL TIPO D",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -3,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N17 CONTROLADOR INCIDENCIAS REC HUM 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 25.00
	},
	{
		"CATEGORIA" : "N40 SUBJ ENF UM D      80",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 70.00
	},
	{
		"CATEGORIA" : "ORIENT ACT ARTIS MUSIC 20",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -3,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N22 VISITADOR          80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 62.50
	},
	{
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "N17 LOCALIZADOR PATRON 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "JEFE DE LINEA EN TIENDA80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "N17 CENSOR CONSTRUC    80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "QUIMICO CLINICO        80",
		"PLAZAS_OCUPADAS" : 187,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 185,
		"PORCENTAJE_OCUPACION" : 98.94
	},
	{
		"CATEGORIA" : "ORIENT TECNICO MEDICO  20",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 71.43
	},
	{
		"CATEGORIA" : "AUX ADMON UNID MEDICA  80",
		"PLAZAS_OCUPADAS" : 57,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 55,
		"PORCENTAJE_OCUPACION" : 96.61
	},
	{
		"CATEGORIA" : "AYUDANTE DE FARMACIA   80",
		"PLAZAS_OCUPADAS" : 43,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 41,
		"PORCENTAJE_OCUPACION" : 95.56
	},
	{
		"CATEGORIA" : "ORIENT ACT ART ARTE DRA20",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N38 AUDITOR A PATR A   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "ORIENT ACT ARTISTICAS  20",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N53 JEFE DEPTO DELEG 3 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 71.43
	},
	{
		"CATEGORIA" : "TECNICO RADIOLOGO      80",
		"PLAZAS_OCUPADAS" : 121,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 119,
		"PORCENTAJE_OCUPACION" : 98.37
	},
	{
		"CATEGORIA" : "TECNICO DE BIBLIOTECAS 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "ANALISTA E2",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N31 ADMOR CSS UD Y CA  80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "N25 TECNICA ATN OR DER 80",
		"PLAZAS_OCUPADAS" : 14,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 87.50
	},
	{
		"CATEGORIA" : "AUX TEC SERVS DIET     80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N41 SUBJ ENF UM C      80",
		"PLAZAS_OCUPADAS" : 23,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 21,
		"PORCENTAJE_OCUPACION" : 92.00
	},
	{
		"CATEGORIA" : "OFICIAL DE PERSONAL    80",
		"PLAZAS_OCUPADAS" : 47,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 45,
		"PORCENTAJE_OCUPACION" : 95.92
	},
	{
		"CATEGORIA" : "N49 JEFE OFNA SUBDEL 4 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 71.43
	},
	{
		"CATEGORIA" : "ORIENT ACT ART DANZA   20",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "OP MAQUINA DE REV AUT  80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 71.43
	},
	{
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N49 JEFE OFNA DELEG 3  80",
		"PLAZAS_OCUPADAS" : 31,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 29,
		"PORCENTAJE_OCUPACION" : 93.94
	},
	{
		"CATEGORIA" : "GUARDAVIDAS 65",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "TEC OP TRANS PAC URG   80",
		"PLAZAS_OCUPADAS" : 29,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 27,
		"PORCENTAJE_OCUPACION" : 93.55
	},
	{
		"CATEGORIA" : "N47 JEFE DEPTO UMH A   80",
		"PLAZAS_OCUPADAS" : 11,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 9,
		"PORCENTAJE_OCUPACION" : 84.62
	},
	{
		"CATEGORIA" : "ORIENT ACT ART DANZA   40",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "AUX DE ENF SALUD PUB   80",
		"PLAZAS_OCUPADAS" : 137,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 135,
		"PORCENTAJE_OCUPACION" : 98.56
	},
	{
		"CATEGORIA" : "CIRUJANO MAXILO-FACIAL 80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N17 ASISTENTE ADMVO C  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 33.33
	},
	{
		"CATEGORIA" : "N15 SRIA J DEPTO SUBD4 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N15 SRIA J OF C CO IMSS80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"PLAZAS_OCUPADAS" : 19,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 95.00
	},
	{
		"CATEGORIA" : "N30 CONT SIST INTER D  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N39 JEFE ENFERM UMF 3  80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N33 ANALISTA A         80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "AUDIT A PATRONES E0",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 92.86
	},
	{
		"CATEGORIA" : "N25 SUBJ TRAB SOC UMH  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N51 DIRECTOR UMH E     80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 92.86
	},
	{
		"CATEGORIA" : "N51 JEFE OFICINA GUARD OOAD 3 Y 4 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N27 CAJERO TIT D3Y4    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "TEC A FLUIDOS-ENERGET  80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 92.86
	},
	{
		"CATEGORIA" : "N49 AUDITOR AREA AUD QR80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "TECNICO ELECTRICISTA   80",
		"PLAZAS_OCUPADAS" : 21,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 20,
		"PORCENTAJE_OCUPACION" : 95.45
	},
	{
		"CATEGORIA" : "TECNICO DE BIBLIOTECAS 65",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "CENSOR CONSTRUCCION E0",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "JEFE OFICINA SUBDELEG E3",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 88.89
	},
	{
		"CATEGORIA" : "CONTROLADOR SIST INTERACTIVO E3",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N25 JEF D NUT DIE UMHD 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N45 RESID C PROY CONST 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "LOCALIZADOR PATRONES E0",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "N34 CONTADOR TIENDA B  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N39 INSTRUCTOR(A) CAPACITACION A 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "N53 JEFE DEPTO SUBDEL4 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N44 ESP SEGURIDAD TRABAJO",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "N53 DIRECTOR  UMF 2    80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N39 TEC ESP A CON D3Y4 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "COOR DE SERVS TECNICOS 80",
		"PLAZAS_OCUPADAS" : 42,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 41,
		"PORCENTAJE_OCUPACION" : 97.67
	},
	{
		"CATEGORIA" : "N13 SRIA D UNID OPERAT 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "ORIENT INIC CULTURAL   40",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "AUX DE LABORATORIO     80",
		"PLAZAS_OCUPADAS" : 56,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 55,
		"PORCENTAJE_OCUPACION" : 98.25
	},
	{
		"CATEGORIA" : "AUX SERVS GRALES U MED 80",
		"PLAZAS_OCUPADAS" : 32,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 31,
		"PORCENTAJE_OCUPACION" : 96.97
	},
	{
		"CATEGORIA" : "N44 ANALISTA COORD A   80",
		"PLAZAS_OCUPADAS" : 9,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 90.00
	},
	{
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 85.71
	},
	{
		"CATEGORIA" : "N15 SRIA J OFNA SUBD 4 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N52 DIRECTOR UMF 3     80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "OFICIAL DE ESTADISTICA 80",
		"PLAZAS_OCUPADAS" : 62,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 61,
		"PORCENTAJE_OCUPACION" : 98.41
	},
	{
		"CATEGORIA" : "N41 JEFE B CONSER UNID 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "ASISTENTE INFORMACION E2",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "EDUCADORA              40",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 80.00
	},
	{
		"CATEGORIA" : "HISTOTECNOLOGO         80",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 87.50
	},
	{
		"CATEGORIA" : "OF SERVS DE LAVANDERIA 80",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 87.50
	},
	{
		"CATEGORIA" : "N45 JEFE DEPTO UMH B   80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 85.71
	},
	{
		"CATEGORIA" : "ESPECIAL CLASIFICACION EMPRESAS E0",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "ENC AUDITORIA PATRONES SUBDELEG E2",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "TEC MANEJO AP ELECTRODI80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 85.71
	},
	{
		"CATEGORIA" : "N17 SRIA COORD SUBD 4  80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N36 TEC SEG E HIG TRAB 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N41 ADMINISTRADOR UMF 280",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "CHOFER                 80",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 88.89
	},
	{
		"CATEGORIA" : "N51 JEFE OFNA OOAD 3 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "TEC B EQUIPOS MEDICOS  80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 9,
		"PORCENTAJE_OCUPACION" : 90.91
	},
	{
		"CATEGORIA" : "N43 JEFE DEPTO UMH C   80",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 93.75
	},
	{
		"CATEGORIA" : "N15 SRIA SUBDELEGADO 2 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N41 RESP PROY SUBD 3   80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "CAMILLERO EN UNIDADES HOSPITALARIAS 80",
		"PLAZAS_OCUPADAS" : 183,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 182,
		"PORCENTAJE_OCUPACION" : 99.46
	},
	{
		"CATEGORIA" : "N54 SUP ESTOM 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "JEFE OFICINA E3",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "JEFE OFICINA SUBDELEG E4",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N26 EJEC OFNA COBR IMSS80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N12 SUBJ CJAS TIENDA AB80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "JEFE DE OFICINA A      80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "TEC MANEJO AP ELECTRODI60",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "OPERADOR TELEFONICO A  80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "ENF ESPEC SALUD PUBL   80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 92.86
	},
	{
		"CATEGORIA" : "N27 J OFNA TEC ADMVA 3 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N44 RES SAN FARM HOSP 2DO NIVEL TIPO A",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N47 JEFE OFNA SUBDEL 3 80",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 94.12
	},
	{
		"CATEGORIA" : "N25 J O DIE ENS UMH AYB80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N41 JEFE ENFERM UM D   80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "OF DE SERVS TECNICOS   80",
		"PLAZAS_OCUPADAS" : 65,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 64,
		"PORCENTAJE_OCUPACION" : 98.48
	},
	{
		"CATEGORIA" : "PSICOLOGO              80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "N41 DIR U OP PRES SOC C80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N39 RES SAN FARM HOSP 2DO NIVEL TIPO C",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N25 CONFIANZA NIVEL    80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N41 COOR CURSOS ENF    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "TEC ATN DERECHOHABIENTE E0",
		"PLAZAS_OCUPADAS" : 38,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 37,
		"PORCENTAJE_OCUPACION" : 97.44
	},
	{
		"CATEGORIA" : "SUPERV PROYECTOS E2",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N30 ADMOR DE TEATRO DF 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N47 COORD ZON GUAR D3Y480",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 87.50
	},
	{
		"CATEGORIA" : "N37 CONTADOR TIENDA A  80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "AUDIT AREA AUDIT QUEJAS RESPONSAB E0",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 80.00
	},
	{
		"CATEGORIA" : "TRABAJADORA SOCIAL     80",
		"PLAZAS_OCUPADAS" : 74,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 73,
		"PORCENTAJE_OCUPACION" : 98.67
	},
	{
		"CATEGORIA" : "N22 J OFNA TEC ADMVA 1 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N51 JEFE DEPTO SUBDEL3 80",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 88.89
	},
	{
		"CATEGORIA" : "N13 INST BASIC ENS CSS 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "CONTROLADOR SIST INTERACTIVO E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N44 COOR OP CAPACIT DIFUS",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "SUPERV INSTALS CONSTRUCCIONES E2",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N19 ENC BOD O COB IMSS 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 75.00
	},
	{
		"CATEGORIA" : "ORIENT TECNICO MEDICO  40",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "LABORATORISTA          80",
		"PLAZAS_OCUPADAS" : 66,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 65,
		"PORCENTAJE_OCUPACION" : 98.51
	},
	{
		"CATEGORIA" : "AUX ADMON UNID MEDICA  65",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 88.89
	},
	{
		"CATEGORIA" : "N30 SUBJ SER BAS UNI A 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "ESP DE SERVS TECNICOS  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ESP DE CONTABILIDAD    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N47 AUX DE APOYO OPERATIVO D3 Y D4 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TERAPISTA OCUPACIONAL  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "CITOTECNOLOGO          80",
		"PLAZAS_OCUPADAS" : 14,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N52 SUBDIR MEDICO UMF  80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N42 SUP SIST INF SALUD 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "BIBLIOTECARIO          80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N30 ADMOR UMF 5        80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "CONSULTORA AL DERECHOHABIENTE E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ENF TRAS PAC URGENCIA  80",
		"PLAZAS_OCUPADAS" : 11,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 11,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 MED SUP EPIDEMIOLOGO 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "JEFE GPO ESTADISTICA   80",
		"PLAZAS_OCUPADAS" : 14,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COOR SOPORTE TEC INFORMAT",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "CONTROLADOR INCIDENCIAS REC HUM E0",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PSICOLOGO EVALUADOR E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED INVEST D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX SOPORTE TEC INFORMAT",
		"PLAZAS_OCUPADAS" : 41,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 41,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OFICIAL PUERICULTURA   80",
		"PLAZAS_OCUPADAS" : 46,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 46,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N39 RESP PROY SUBD 2   80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ANALISTA SUPERVISOR E1",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ESP DE ESTADISTICA     80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N53 JEFE CENTRO DE MEZCLAS 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ENFERMERA JEFE DE PISO 80",
		"PLAZAS_OCUPADAS" : 188,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 188,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 COO D NUT DIE D3Y4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N25 DISENADOR GRAFICO  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ASISTENTE INFORMACION E1",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OF DE SERVS ADMVOS     80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PSICOLOGO CLINICO      80",
		"PLAZAS_OCUPADAS" : 9,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 9,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N41 SUP ASIST MED 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N29 TEC EST SOC SAL TRA80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "INHALOTERAPEUTA        65",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 COOR TEC OR INF DEL B",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 ADMOR UMH D        80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N22 ASISTENTE ADMVO B  80",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORDINADOR DE FARMACIA80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PROF EDUC FISICA A     80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N36 JEF D NUT DIE UMHA 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 DIRECTOR UMF 1     80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 DIRECTORA GUARD A  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED SALUD TRAB D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "JEFE GPO DE PERSONAL   80",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 ADMON SIST INF SALUD D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AYUDANTE DE AUTOPSIA   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N46 JEFE LABORATORIO   80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TEC B FLUIDOS-ENERGET  80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD DE ESTADISTICA   80",
		"PLAZAS_OCUPADAS" : 38,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 38,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 COORD(A) AUX OPER ADMVO D3 Y D4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "SECRETARIA E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N39 DIR U OP PRES SOC D80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N42 COOR D ASIS ME D3Y480",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESIDENTE 4            80",
		"PLAZAS_OCUPADAS" : 39,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 39,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD TEC QUEJAS DERECHOHA E1",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N39 JEFE C CONSER UNID 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 ABOGADO PROCURADOR 80",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD DE SERVS ADMVOS  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "INHALOTERAPEUTA        80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N42 JEFE ENFERM UM C   80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N46 ENF SUP SAL PUBLICA 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OF SOPORTE TEC INFORMAT",
		"PLAZAS_OCUPADAS" : 9,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 9,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OPERADOR AMBULANCIAS 80",
		"PLAZAS_OCUPADAS" : 51,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 51,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "LABORATORISTA          60",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N36 AUDITOR A PATR B   80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESP PROYECTOS E4",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) PLAN ENL INST D3 Y D4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N36 JEF TRAB SOC UMH A 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX ENFERMERIA U M     80",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N52 RESPONSABLE PROY B 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TECNICO PUERICULTURA   80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N18 CAJ AUX SUBD3 Y 4  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TECNICO RADIOLOGO      60",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 13,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N36 SUBJEF A CONS UNID 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX TECNICO E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OFICIAL DE TESORERIA   80",
		"PLAZAS_OCUPADAS" : 49,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 49,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) INF AN EST D3 Y D4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 EVALUADOR PRESCRIPCION CM 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N13 JEFE AREA TIENDA   80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED SAL PUBLICA D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 DIRECTOR UMH B     80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N62 JEFE GPO AREA AUD QR80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 JEFE A CONSER UNID 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N20 TEC INF C CTR P INV80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 MED SUP HOSPITALES 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 COORD Z SEG TRAB D3",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 COORD TEC ANALISIS Y ESTADIST DEL B",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"PLAZAS_OCUPADAS" : 21,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 21,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N25 ASISTENTE ADMVO A  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COCINERO TECNICO 1     80",
		"PLAZAS_OCUPADAS" : 22,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 22,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N27 JEF TRAB SOC UMF   80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N39 CONT SIST INTER A  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "EDUCADORA              65",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX SEG TRAB D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD DE PERSONAL      80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 13,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "SECRETARIA E3",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "HISTOTECNOLOGO         60",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N41 ADMOR TIENDA B     80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ORIENT ACT ARTISTICAS  40",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 JEFE(A) DEPTO CAPACIT Y TRANSP D3 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N30 JEF D NUT DIE UMHC 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N24 CAJERO AYTE D3 Y 4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N62 JEFE(A) SERVS PREST MEDICAS D3 Y D4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 COORDINADOR PREPARADORES CM 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX DE TRAB SOCIAL     80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N46 ENF SUP ATN MED 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESIDENTE 3            80",
		"PLAZAS_OCUPADAS" : 203,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 203,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AYUD DE ABOGADO E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ESP NUTRIC DIETETICA   80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N33 JEF TRAB SOC UMH B 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 COORD DEL ENF SAL PUBLICA D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N47 SOPORTE TEC ESP D3 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N13 SRIA J DEPTO SUBD3 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "VISITADOR E0",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ANALISTA DELEG DE PLANEACION E0",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "SECRETARIA E4",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "MANEJADOR ALIMENTOS    65",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "JEFE GRUPO SERVS TEC   80",
		"PLAZAS_OCUPADAS" : 28,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 28,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ANALISTA SUPERVISOR E2",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ESP DE TESORERIA       80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N42 ANALISTA INF EPIDEMIOLOGICA 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESPONSABLE CALIDAD CM E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N34 JEFE MERC TIENDA A 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PROF EDUC FISICA C     60",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TERAPISTA FISICO       60",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 SUP NUTRI DIET 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N36 INSTRUCTOR(A) CAPACITACION B 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TEC EQ RECIPROCANTES   80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "JEFE GPO CONTABILIDAD  80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESP SANITARIO ALMACEN DEL E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 COORD HOSP DON ORG Y TEJ UMH",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 COORD AUX EST DEL3 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ESPECIAL SEG EN EL TRABAJO E0",
		"PLAZAS_OCUPADAS" : 11,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 11,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX SERVS GRALES U MED 65",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N36 CONSULTORA ATN O D 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TEC ESPECIAL APOYO CONSERVACION E2",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ORIENT ACT ART MUSICA  40",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "NUTRIOLOGO CLIN ESPEC",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 ADMINISTRADOR UMF 180",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N34 SUBJEF BC CON UNID 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) SALUD TRAB D3 Y D4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OPERADOR AMBULANCIAS 65",
		"PLAZAS_OCUPADAS" : 14,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N36 PSIC EVA COM LAB D380",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 COORD DEL TS D3Y4  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N29 JEFE MERC TIENDA B 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX ADMVO E1",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N53 SUBDIR ADMVO UMH B 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N33 PROM SERV PRES SOC 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 CONFIANZA NIVEL    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD DE TESORERIA     80",
		"PLAZAS_OCUPADAS" : 39,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 39,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N20 CONT REC E INC DEL 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 RESP MESA ATENCION CM 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N41 SUBJ ENF UM B      80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 13,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX ATN MED D3YD4 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESIDENTE 2            80",
		"PLAZAS_OCUPADAS" : 213,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 213,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N60 COORD MEDIOS D3Y4  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TEC C FLUIDOS-ENERGET  80",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TECNICO MECANICO       80",
		"PLAZAS_OCUPADAS" : 23,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 23,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N27 ANALISTA D         80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N47 LIDER PROYECTO C   80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 13,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N17 SRIA SUBDELEGADO 3 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 DIR U OP PRES SOC B80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD ASIST MEDICAS    80",
		"PLAZAS_OCUPADAS" : 39,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 39,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N33 JEF D NUT DIE UMHB 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 MED SUP MED FAM 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N52 JEFE CLIN SAL TRAB 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "CONTROLADOR SIST INTERACTIVO E4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 COORD LIMP E HIG OOAD TIPO 3 Y 4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PROF EDUC FISICA C     80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESP AUSENTISMO NO PROG OOAD E3",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 DIRECTOR UMF       80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX TECNICO E1",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "EDUCADORA              80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX ADMVO E3",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 RESP PROY SUBD 4   80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED EPIDEMIOLOGI D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESPONSABLE PREPARACION CM E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N44 ADMOR TIENDA A     80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) GEST MEDICA D3 Y D4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N52 SUBDIR ADMVO UMH C 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD DE CONTABILIDAD  80",
		"PLAZAS_OCUPADAS" : 19,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 19,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "AUX RESP SANITARIO ALMACEN E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ABOGADO                80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PROF EDUC FISICA C     40",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "PSICOLOGO CLINICO      60",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 COORD DEL ENF ATN MED D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N02 CONFIANZA NIVEL    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 SUBDIR ADMVO UMH A 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 MED SUP LIDER 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N18 J SEC PROD DIE UMH 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"PLAZAS_OCUPADAS" : 29,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 29,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N36 SUPERV INSTAL B    80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TEC EQ HELICOIDAL      80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 DIR CENT REG STCYP",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD PROYECTO E1",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "OPERADOR TELEFONICO B  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ESP DE PERSONAL        80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED EDUCA D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N43 JEFE ENFERM UM A   80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N23 AUX ENTRENADOR     80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "SUPERV AUDITORIA PATRONES E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TEC ELECT MED LAB      80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "INSTRUCTOR(A) CAPACITACION E2",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "JEFE DE GPO DE TESORER 80",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ING BIOMEDICO E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 ANALISTA DE CALIDAD CM 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "ESTOMATOLOGO           80",
		"PLAZAS_OCUPADAS" : 85,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 85,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 DIRECTOR UMH C     80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N59 COORDINADOR(A) PREV ATN SAL D3 Y D4",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESIDENTE 1            80",
		"PLAZAS_OCUPADAS" : 238,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 238,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TECNICO ELECTRONICO    80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TEC EQ TURBOCENTRIFUGO 80",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "JEFE(A) DEPARTAMENTO LABORAL E3",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORDINADOR DE ALMACEN 80",
		"PLAZAS_OCUPADAS" : 7,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 7,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TERAPISTA FISICO       80",
		"PLAZAS_OCUPADAS" : 23,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 23,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "RESP PROYECTOS E3",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 SUBDIR MED UMH B   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED SPPSTIMSS D3YD4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 MEDICO ESP ST      80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N33 ADMINISTRADOR UMF 580",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "SUPERV INSTALACIONES E2",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TRABAJADOR SOCIAL CLINICO",
		"PLAZAS_OCUPADAS" : 14,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "MENSAJERO              80",
		"PLAZAS_OCUPADAS" : 9,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 9,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COCINERO TECNICO 2     80",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N48 DIRECTOR MICROZONA 80",
		"PLAZAS_OCUPADAS" : 5,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N31 ADMOR GUARDERIA    80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N30 JEF TRAB SOC UMH C 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "TEC MEC FLUIDOS ESPEC  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N42 ANALISTA INF SALUD D3YD4 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N51 JEFE DE LABORATORIO UMH 80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N17 JEFE CAJ TIENDA    80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX GEST MED D3YD4 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	}
];
