/*
SELECT 
    CASE 
        WHEN RJP = 'C108' THEN 'CUOTA SINDICAL'
        WHEN RJP = 'C111' THEN 'APORTACIÓN COMPLEMENTARIA AFORE'
        WHEN RJP = 'C152' THEN 'FONDO DE JUBILACIÓN'
        WHEN RJP = 'C152 Y C107' THEN 'FONDO DE JUBILACIÓN + NIVELACIÓN A PLAZA SUPERIOR'
        WHEN RJP = 'ESTATUTO' THEN 'ESTATUTO'
        WHEN RJP = 'SIN RJP' THEN 'SIN RÉGIMEN DE JUBILACIONES Y PENSIONES'
        ELSE RJP
    END AS RJP_DESCRIPCION,
    COUNT(*) AS cantidad
FROM personalaps.plantillaordinario
WHERE QNA = '2024017'
AND PLZOCU = 1
AND NUMDEL = '26'
AND DELEGACION = 'Sinaloa'
GROUP BY RJP_DESCRIPCION
ORDER BY cantidad DESC;
*/
var dona = [
	{
		"RJP_DESCRIPCION" : "APORTACIÓN COMPLEMENTARIA AFORE",
		"cantidad" : 8596
	},
	{
		"RJP_DESCRIPCION" : "FONDO DE JUBILACIÓN + NIVELACIÓN A PLAZA SUPERIOR",
		"cantidad" : 2235
	},
	{
		"RJP_DESCRIPCION" : "CUOTA SINDICAL",
		"cantidad" : 862
	},
	{
		"RJP_DESCRIPCION" : "ESTATUTO",
		"cantidad" : 191
	},
	{
		"RJP_DESCRIPCION" : "SIN RÉGIMEN DE JUBILACIONES Y PENSIONES",
		"cantidad" : 1
	}
];