/* query para crear la tabla plazas ocupadas y vacantes por OOAD ejecutar el siguiente query
SELECT
	p.NUMDEL,
	p.DELEGACION,
	COUNT(DISTINCT p.DEPENDENCIA) AS TOTAL_UNIDADES,
	SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) AS OCUPADAS,
	SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) AS VACANTES,
	ROUND(SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) * 100.0 / 
		NULLIF(SUM(CASE WHEN p.PLZOCU = 1 OR p.PLZVAC = 1 THEN 1 ELSE 0 END), 0), 2) AS PORCENTAJE_OCUPADAS,
	ROUND(SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) * 100.0 / 
		NULLIF(SUM(CASE WHEN p.PLZOCU = 1 OR p.PLZVAC = 1 THEN 1 ELSE 0 END), 0), 2) AS PORCENTAJE_VACANTES
FROM 
	personalaps.plantillaordinario p
WHERE QNA = '2024017'
AND NUMDEL = '26'
AND DELEGACION = 'Sinaloa'
GROUP BY
	p.NUMDEL, p.DELEGACION
ORDER BY
	p.NUMDEL;
	
*/

const datosDelegaciones = [
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"TOTAL_UNIDADES" : 87,
		"OCUPADAS" : 11885,
		"VACANTES" : 783,
		"PORCENTAJE_OCUPADAS" : 93.82,
		"PORCENTAJE_VACANTES" : 6.18
	}
];

/* query para extraer esta información del modal desagregado
SELECT 
    p.NUMDEL, 
    p.DELEGACION, 
    p.CATEGORIA AS CATEGORIA, 
    p.DESCRIP_CLASCATEG AS DESCRIPCION,
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) AS VACANTES
FROM 
    personalaps.plantillaordinario p
WHERE p.DESCRIP_CLASCATEG = "1.MÉDICOS"
GROUP BY 
    p.NUMDEL, p.DELEGACION, p.CATEGORIA
HAVING 
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) > 0
ORDER BY 
    p.NUMDEL, p.CATEGORIA;
*/
const datosDelegacionesDesagregado = [
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ABOGADO PROCURADOR E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ANALISTA E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ASISTENTE INFORMACION E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ASISTENTE MEDICA       65",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ASISTENTE MEDICA       80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUDIT A PATRONES E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUDIT AREA AUDIT QUEJAS RESPONSAB E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX ADMON UNID MEDICA  65",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX ADMON UNID MEDICA  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX ADMVO E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX DE ENF SALUD PUB   80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX DE ENFERMERIA GRAL 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX DE LABORATORIO     80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX DE SERVS DE INT    65",
		"DESCRIPCION" : "6.BÁSICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX DE SERVS DE INT    80",
		"DESCRIPCION" : "6.BÁSICOS",
		"VACANTES" : 14
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX DE TRAB SOCIAL     65",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX LIMPIEZA E HIGIENE UM Y NO MED 80",
		"DESCRIPCION" : "6.BÁSICOS",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX SERVS GRALES U MED 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX TEC SERVS DIET     80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX UNIV DE OFICINAS   65",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUX UNIV DE OFICINAS   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 32
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUXILIAR DE ALMACEN    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 6
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AUXILIAR DE FARMACIA   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 13
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AYTE LIMPIEZA E HIGIENE UM Y NO MED 80",
		"DESCRIPCION" : "6.BÁSICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "AYUDANTE DE FARMACIA   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "CAMILLERO EN UNIDADES HOSPITALARIAS 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "CENSOR CONSTRUCCION E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "CHOFER                 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "CIRUJANO MAXILO-FACIAL 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "CONTROLADOR SIST INTERACTIVO E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "CONTROLADOR SIST INTERACTIVO E3",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "COOR DE SERVS TECNICOS 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "EDUCADORA              40",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ENC AUDITORIA PATRONES SUBDELEG E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ENF ESPEC SALUD PUBL   80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ENFERMERA ESPECIALISTA 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 13
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ENFERMERA GENERAL      80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 18
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ENFERMERA GENERAL CLINICA 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 137
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ESPECIAL CLASIFICACION EMPRESAS E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "GUARDAVIDAS 65",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "HISTOTECNOLOGO         80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "JEFE DE LINEA EN TIENDA80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "JEFE DE OFICINA A      80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "JEFE OFICINA E3",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "JEFE OFICINA SUBDELEG E3",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "JEFE OFICINA SUBDELEG E4",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "LABORATORISTA          80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "LOCALIZADOR PATRONES E0",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MANEJADOR ALIMENTOS    80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 23
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MEDICO GENERAL 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 16
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 49
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "MENSAJERO              65",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N12 OP  CAJAS TIENDA   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 12
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N12 SRIA E UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N12 SUBJ CJAS TIENDA AB80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N13 INST BASIC ENS CSS 80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N13 SRIA D UNID OPERAT 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N15 SRIA J DEPTO SUBD4 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N15 SRIA J OF C CO IMSS80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N15 SRIA J OFNA SUBD 4 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N15 SRIA SUBDELEGADO 2 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N17 ASISTENTE ADMVO C  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N17 CENSOR CONSTRUC    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N17 CONTROLADOR INCIDENCIAS REC HUM 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N17 LOCALIZADOR PATRON 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N17 SRIA COORD SUBD 4  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N19 ENC BOD O COB IMSS 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N21 PROMOTOR(A) SAL INTEG PREVENIMSS 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N22 J OFNA TEC ADMVA 1 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N22 VISITADOR          80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N24 SUBJ SER BAS UNI C 80",
		"DESCRIPCION" : "6.BÁSICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N25 CONFIANZA NIVEL    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N25 J O DIE ENS UMH AYB80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N25 JEF D NUT DIE UMHD 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N25 SUBJ TRAB SOC UMH  80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N25 TECNICA ATN OR DER 80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N26 EJEC OFNA COBR IMSS80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N27 CAJERO TIT D3Y4    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N27 J OFNA TEC ADMVA 3 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N30 ADMOR DE TEATRO DF 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N30 ANALISTA C         80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N30 CONT SIST INTER D  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N30 SUBJ SER BAS UNI A 80",
		"DESCRIPCION" : "6.BÁSICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N31 ADMOR CSS UD Y CA  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N32 JEFE LIMP E HIG UMAE HGR HGZ 80",
		"DESCRIPCION" : "6.BÁSICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N33 ANALISTA A         80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N34 CONTADOR TIENDA B  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N36 ANALISTA RESP D    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N36 RES SAN FARM HOSP 2DO NIVEL TIPO D",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N36 TEC SEG E HIG TRAB 80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N37 CONTADOR TIENDA A  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N38 AUDITOR A PATR A   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N39 ANALISTA RESP B    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N39 INSTRUCTOR(A) CAPACITACION A 80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N39 JEFE ENFERM UMF 3  80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N39 RES SAN FARM HOSP 2DO NIVEL TIPO C",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N39 SUPERVISOR LIMPIEZA E HIGIENE 80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N39 TEC ESP A CON D3Y4 80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N40 SUBJ ENF UM D      80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 ADMINISTRADOR UMF 280",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 ANALISTA COORD C   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 COOR CURSOS ENF    80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 DIR U OP PRES SOC C80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 JEFE B CONSER UNID 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 JEFE ENFERM UM D   80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 RES SAN FARM HOSP 2DO NIVEL TIPO B",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 RESP PROY SUBD 3   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 SUBJ ENF UM A      80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N41 SUBJ ENF UM C      80",
		"DESCRIPCION" : "2.ENFERMERAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N43 JEFE DEPTO UMH C   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N44 ANALISTA COORD A   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N44 COOR OP CAPACIT DIFUS",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N44 ESP SEGURIDAD TRABAJO",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N44 RES SAN FARM HOSP 2DO NIVEL TIPO A",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N44 RESP PROY D3       80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N45 JEFE DEPTO UMH B   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N45 RESID C PROY CONST 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N47 COORD ZON GUAR D3Y480",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N47 JEFE DEPTO UMH A   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N47 JEFE OFNA SUBDEL 3 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N49 AUDITOR AREA AUD QR80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N49 JEFE OFNA DELEG 3  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N49 JEFE OFNA SUBDEL 4 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 DIRECTOR UMH E     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 JEFE DEPTO SUBDEL3 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 JEFE OFICINA GUARD OOAD 3 Y 4 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 JEFE OFNA OOAD 3 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 18
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N52 DIRECTOR UMF 3     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N53 DIRECTOR  UMF 2    80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N53 JEFE DEPTO DELEG 3 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N53 JEFE DEPTO SUBDEL4 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N54 SUP ESTOM 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"DESCRIPCION" : "1.MÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "NUTRICIONISTA DIETISTA 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OF DE SERVS TECNICOS   80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OF SERVS DE LAVANDERIA 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OFICIAL DE ALMACEN     80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 7
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OFICIAL DE ESTADISTICA 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OFICIAL DE FARMACIA    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OFICIAL DE PERSONAL    80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OFICIAL PUERICULTURA   65",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 13
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OP GRAL EN TIENDAS     80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 20
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OP MAQUINA DE REV AUT  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OP SERVS DE LAVANDERIA 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OPERADOR TELEFONICO A  65",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "OPERADOR TELEFONICO A  80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT ACT ART ARTE DRA20",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT ACT ART DANZA   20",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT ACT ART DANZA   40",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT ACT ARTIS MUSIC 20",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT ACT ARTISTICAS  20",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT ACT ARTISTICAS  33",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT ACT FAMILIARES  20",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 17
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT ACT FAMILIARES  40",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT INIC CULTURAL   20",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT INIC CULTURAL   40",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT TECNICO MEDICO  20",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "ORIENT TECNICO MEDICO  40",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "PREPARADOR DE MEZCLAS 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 15
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "PROF EDUC FISICA A     40",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "PROM SALUD COMUNITARIA 80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "PSICOLOGO              80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "QUIMICO CLINICO        80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "SUPERV INSTALS CONSTRUCCIONES E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "SUPERV PROYECTOS E2",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TEC A AIRE ACON REFRIG 80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TEC A EQUIPOS MEDICOS  80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 5
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TEC A FLUIDOS-ENERGET  80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TEC ATN DERECHOHABIENTE E0",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TEC B EQUIPOS MEDICOS  80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TEC MANEJO AP ELECTRODI60",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TEC MANEJO AP ELECTRODI80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TEC OP TRANS PAC URG   80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TECNICO DE BIBLIOTECAS 65",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TECNICO DE BIBLIOTECAS 80",
		"DESCRIPCION" : "5.ADMINISTRATIVAS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TECNICO ELECTRICISTA   80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 1
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TECNICO PLOMERO        80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 4
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TECNICO POLIVALENTE    80",
		"DESCRIPCION" : "4.TÉCNICOS",
		"VACANTES" : 17
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TECNICO RADIOLOGO      80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 2
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TRABAJADORA SOCIAL     65",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 3
	},
	{
		"NUMDEL" : "26",
		"DELEGACION" : "Sinaloa",
		"CATEGORIA" : "TRABAJADORA SOCIAL     80",
		"DESCRIPCION" : "3.PARAMÉDICOS",
		"VACANTES" : 1
	}
];