/*Extraer este es un problema pero estos son los querys aplicados paso por paso para hacerlo

-- Numero 1

CREATE TABLE procesado.plazas_vacantes_por_estado_TOTAL AS
SELECT
    p.NUMDEL,
    CASE
        WHEN p.NUMDEL IN ('31', '32') THEN '30' -- Agrupa Veracruz Norte y Sur como 30
        WHEN p.NUMDEL IN ('35', '36', '37', '38') THEN '09' -- Agrupa Ciudad de México (DF Norte y Sur) como 09
        WHEN p.NUMDEL IN ('15', '16') THEN '15' -- Agrupa México Oriente y Poniente como 15
        ELSE p.NUMDEL -- Deja los demás estados igual
    END AS NUMELINEGI,
    p.DELEGACION,
    COUNT(DISTINCT p.DEPENDENCIA) AS TOTAL_UNIDADES,
    SUM(CASE WHEN p.PLZOCU = 1 THEN 1 ELSE 0 END) AS OCUPADAS,
    SUM(CASE WHEN p.PLZVAC = 1 THEN 1 ELSE 0 END) AS VACANTES
FROM
    personalaps.plantillaordinario p
WHERE DESCRIP_CLASCATEG = '1.MÉDICOS'
AND p.QNA = '2024017'
GROUP BY
    NUMELINEGI, p.NUMDEL, p.DELEGACION
ORDER BY
    NUMELINEGI, p.NUMDEL;

SELECT * FROM procesado.plazas_vacantes_por_estado_TOTAL;


-- Numero 2

UPDATE procesado.plazas_vacantes_por_estado_TOTAL
SET NUMELINEGI = 
    CASE 
        WHEN DELEGACION = 'Michoacán' THEN '16'
        WHEN DELEGACION = 'Morelos' THEN '17'
        WHEN DELEGACION = 'Nayarit' THEN '18'
        WHEN DELEGACION = 'Nuevo León' THEN '19'
        WHEN DELEGACION = 'Oaxaca' THEN '20'
        WHEN DELEGACION = 'Puebla' THEN '21'
        WHEN DELEGACION = 'Querétaro' THEN '22'
        WHEN DELEGACION = 'Quintana Roo' THEN '23'
        WHEN DELEGACION = 'San Luis Potosí' THEN '24'
        WHEN DELEGACION = 'Sinaloa' THEN '25'
        WHEN DELEGACION = 'Sonora' THEN '26'
        WHEN DELEGACION = 'Tabasco' THEN '27'
        WHEN DELEGACION = 'Tamaulipas' THEN '28'
        WHEN DELEGACION = 'Tlaxcala' THEN '29'
        WHEN DELEGACION = 'Veracruz Norte' THEN '30'
        WHEN DELEGACION = 'Veracruz Sur' THEN '30'
        WHEN DELEGACION = 'Yucatán' THEN '31'
        WHEN DELEGACION = 'Zacatecas' THEN '32'
        ELSE NUMELINEGI
    END
WHERE DELEGACION IN ('Michoacán', 'Morelos', 'Nayarit', 'Nuevo León', 'Oaxaca', 
                     'Puebla', 'Querétaro', 'Quintana Roo', 'San Luis Potosí', 
                     'Sinaloa', 'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala', 
                     'Veracruz Norte', 'Veracruz Sur', 'Yucatán', 'Zacatecas');


-- Numero 3

CREATE TABLE procesado.vacantes_estado_densidad_poblacional_TOTAL AS
SELECT
    CASE
        -- Agrupar Veracruz Norte y Sur bajo NUMELINEGI 30
        WHEN pvpe.NUMELINEGI = '30' THEN '30'
        -- Agrupar Ciudad de México (DF Norte y Sur) bajo NUMELINEGI 09
        WHEN pvpe.NUMELINEGI = '09' THEN '09'
        -- Agrupar México Oriente y Poniente bajo NUMELINEGI 15
        WHEN pvpe.NUMELINEGI = '15' THEN '15'
        ELSE pvpe.NUMELINEGI
    END AS NUMELINEGI,
    CASE
        -- Renombrar Veracruz agrupado
        WHEN pvpe.NUMELINEGI = '30' THEN 'Veracruz'
        -- Renombrar Ciudad de México agrupado
        WHEN pvpe.NUMELINEGI = '09' THEN 'Ciudad de México'
        -- Renombrar México agrupado
        WHEN pvpe.NUMELINEGI = '15' THEN 'Estado de México'
        ELSE pvpe.DELEGACION
    END AS DELEGACION,
    SUM(pvpe.TOTAL_UNIDADES) AS TOTAL_UNIDADES,
    SUM(pvpe.OCUPADAS) AS OCUPADAS,
    SUM(pvpe.VACANTES) AS VACANTES,
    SUM(catalogo.imss) AS DERECHOHABIENTES
FROM
    procesado.plazas_vacantes_por_estado_TOTAL pvpe
LEFT JOIN
    personalaps.catalogo_derechohabiencia_estado catalogo
    ON pvpe.NUMELINEGI = catalogo.numero_delegacion
GROUP BY
    NUMELINEGI, DELEGACION
ORDER BY
    NUMELINEGI;

SELECT *  FROM procesado.vacantes_estado_densidad_poblacional_TOTAL;


-- Numero 4

CREATE TABLE procesado.vacantes_estado_densidad_poblacional_agrupado_TOTAL AS
SELECT 
    NUMELINEGI,
    DELEGACION,
    SUM(TOTAL_UNIDADES) AS TOTAL_UNIDADES,
    SUM(VACANTES) AS PLAZAS_VACANTES,
    SUM(OCUPADAS) AS PLAZAS_OCUPADAS,
    MAX(DERECHOHABIENTES) AS DERECHOHABIENTES -- Obtiene cualquier valor (ya que son iguales)
FROM 
    procesado.vacantes_estado_densidad_poblacional_TOTAL
GROUP BY 
    NUMELINEGI, DELEGACION
ORDER BY 
    NUMELINEGI;

SELECT DELEGACION, DERECHOHABIENTES, PLAZAS_OCUPADAS, PLAZAS_VACANTES FROM procesado.vacantes_estado_densidad_poblacional_agrupado_TOTAL;

*/

// 📌 Array de datos SIN base de datos
const datos = [
	{
		"DELEGACION" : "Aguascalientes",
		"DERECHOHABIENTES" : 780525,
		"PLAZAS_OCUPADAS" : 1501,
		"PLAZAS_VACANTES" : 42
	},
	{
		"DELEGACION" : "Baja California",
		"DERECHOHABIENTES" : 1995530,
		"PLAZAS_OCUPADAS" : 2739,
		"PLAZAS_VACANTES" : 160
	},
	{
		"DELEGACION" : "Baja California Sur",
		"DERECHOHABIENTES" : 408856,
		"PLAZAS_OCUPADAS" : 975,
		"PLAZAS_VACANTES" : 80
	},
	{
		"DELEGACION" : "Campeche",
		"DERECHOHABIENTES" : 288186,
		"PLAZAS_OCUPADAS" : 673,
		"PLAZAS_VACANTES" : 50
	},
	{
		"DELEGACION" : "Coahuila",
		"DERECHOHABIENTES" : 2085705,
		"PLAZAS_OCUPADAS" : 3098,
		"PLAZAS_VACANTES" : 349
	},
	{
		"DELEGACION" : "Colima",
		"DERECHOHABIENTES" : 362244,
		"PLAZAS_OCUPADAS" : 836,
		"PLAZAS_VACANTES" : 52
	},
	{
		"DELEGACION" : "Chiapas",
		"DERECHOHABIENTES" : 672681,
		"PLAZAS_OCUPADAS" : 1327,
		"PLAZAS_VACANTES" : 130
	},
	{
		"DELEGACION" : "Chihuahua",
		"DERECHOHABIENTES" : 2043251,
		"PLAZAS_OCUPADAS" : 2967,
		"PLAZAS_VACANTES" : 761
	},
	{
		"DELEGACION" : "Ciudad de México",
		"DERECHOHABIENTES" : 3881545,
		"PLAZAS_OCUPADAS" : 12977,
		"PLAZAS_VACANTES" : 1200
	},
	{
		"DELEGACION" : "Durango",
		"DERECHOHABIENTES" : 744664,
		"PLAZAS_OCUPADAS" : 1260,
		"PLAZAS_VACANTES" : 62
	},
	{
		"DELEGACION" : "Guanajuato",
		"DERECHOHABIENTES" : 2259062,
		"PLAZAS_OCUPADAS" : 3279,
		"PLAZAS_VACANTES" : 146
	},
	{
		"DELEGACION" : "Guerrero",
		"DERECHOHABIENTES" : 506026,
		"PLAZAS_OCUPADAS" : 1154,
		"PLAZAS_VACANTES" : 115
	},
	{
		"DELEGACION" : "Hidalgo",
		"DERECHOHABIENTES" : 744201,
		"PLAZAS_OCUPADAS" : 1425,
		"PLAZAS_VACANTES" : 136
	},
	{
		"DELEGACION" : "Jalisco",
		"DERECHOHABIENTES" : 4149528,
		"PLAZAS_OCUPADAS" : 6643,
		"PLAZAS_VACANTES" : 420
	},
	{
		"DELEGACION" : "Estado de México",
		"DERECHOHABIENTES" : 5983389,
		"PLAZAS_OCUPADAS" : 7902,
		"PLAZAS_VACANTES" : 751
	},
	{
		"DELEGACION" : "Michoacán",
		"DERECHOHABIENTES" : 1207045,
		"PLAZAS_OCUPADAS" : 2142,
		"PLAZAS_VACANTES" : 343
	},
	{
		"DELEGACION" : "Morelos",
		"DERECHOHABIENTES" : 616556,
		"PLAZAS_OCUPADAS" : 1232,
		"PLAZAS_VACANTES" : 92
	},
	{
		"DELEGACION" : "Nayarit",
		"DERECHOHABIENTES" : 464297,
		"PLAZAS_OCUPADAS" : 1223,
		"PLAZAS_VACANTES" : 85
	},
	{
		"DELEGACION" : "Nuevo León",
		"DERECHOHABIENTES" : 3596116,
		"PLAZAS_OCUPADAS" : 5094,
		"PLAZAS_VACANTES" : 213
	},
	{
		"DELEGACION" : "Oaxaca",
		"DERECHOHABIENTES" : 583455,
		"PLAZAS_OCUPADAS" : 1077,
		"PLAZAS_VACANTES" : 46
	},
	{
		"DELEGACION" : "Puebla",
		"DERECHOHABIENTES" : 1445433,
		"PLAZAS_OCUPADAS" : 2419,
		"PLAZAS_VACANTES" : 282
	},
	{
		"DELEGACION" : "Querétaro",
		"DERECHOHABIENTES" : 1121262,
		"PLAZAS_OCUPADAS" : 1706,
		"PLAZAS_VACANTES" : 44
	},
	{
		"DELEGACION" : "Quintana Roo",
		"DERECHOHABIENTES" : 827522,
		"PLAZAS_OCUPADAS" : 1241,
		"PLAZAS_VACANTES" : 108
	},
	{
		"DELEGACION" : "San Luis Potosí",
		"DERECHOHABIENTES" : 1116471,
		"PLAZAS_OCUPADAS" : 1573,
		"PLAZAS_VACANTES" : 147
	},
	{
		"DELEGACION" : "Sinaloa",
		"DERECHOHABIENTES" : 1516933,
		"PLAZAS_OCUPADAS" : 2298,
		"PLAZAS_VACANTES" : 115
	},
	{
		"DELEGACION" : "Sonora",
		"DERECHOHABIENTES" : 1579466,
		"PLAZAS_OCUPADAS" : 3045,
		"PLAZAS_VACANTES" : 395
	},
	{
		"DELEGACION" : "Tabasco",
		"DERECHOHABIENTES" : 498783,
		"PLAZAS_OCUPADAS" : 953,
		"PLAZAS_VACANTES" : 132
	},
	{
		"DELEGACION" : "Tamaulipas",
		"DERECHOHABIENTES" : 1670262,
		"PLAZAS_OCUPADAS" : 2519,
		"PLAZAS_VACANTES" : 326
	},
	{
		"DELEGACION" : "Tlaxcala",
		"DERECHOHABIENTES" : 322989,
		"PLAZAS_OCUPADAS" : 640,
		"PLAZAS_VACANTES" : 19
	},
	{
		"DELEGACION" : "Veracruz",
		"DERECHOHABIENTES" : 2266970,
		"PLAZAS_OCUPADAS" : 4260,
		"PLAZAS_VACANTES" : 489
	},
	{
		"DELEGACION" : "Yucatán",
		"DERECHOHABIENTES" : 980491,
		"PLAZAS_OCUPADAS" : 1907,
		"PLAZAS_VACANTES" : 81
	},
	{
		"DELEGACION" : "Zacatecas",
		"DERECHOHABIENTES" : 526465,
		"PLAZAS_OCUPADAS" : 845,
		"PLAZAS_VACANTES" : 77
	}
];

/*
Query para extraer esta informacion de la tabla plazas ocupadas y vacantes por categoria 

SELECT 
    p.CATEGORIA,
    COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) AS PLAZAS_OCUPADAS,
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END) AS PLAZAS_VACANTES,
    (COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) - 
    COUNT(CASE WHEN p.PLZVAC = 1 THEN p.MATRICULA END)) AS DIFERENCIA,
    ROUND(
    COUNT(CASE WHEN p.PLZOCU = 1 THEN p.MATRICULA END) * 100.0 /
    NULLIF(COUNT(p.MATRICULA), 0), 2
) AS PORCENTAJE_OCUPACION
FROM 
    personalaps.plantillaordinario p
WHERE p.DESCRIP_CLASCATEG = "1.MÉDICOS"
AND p.QNA = '2024017'
GROUP BY 
    p.CATEGORIA
ORDER BY 
    PLAZAS_VACANTES DESC;
*/

const datos8 = [
	{
		"CATEGORIA" : "MEDICO NO FAMILIAR     80",
		"PLAZAS_OCUPADAS" : 46004,
		"PLAZAS_VACANTES" : 4955,
		"DIFERENCIA" : 41049,
		"PORCENTAJE_OCUPACION" : 90.28
	},
	{
		"CATEGORIA" : "MEDICO FAMILIAR        80",
		"PLAZAS_OCUPADAS" : 23294,
		"PLAZAS_VACANTES" : 792,
		"DIFERENCIA" : 22502,
		"PORCENTAJE_OCUPACION" : 96.71
	},
	{
		"CATEGORIA" : "MEDICO GENERAL 80",
		"PLAZAS_OCUPADAS" : 5573,
		"PLAZAS_VACANTES" : 485,
		"DIFERENCIA" : 5088,
		"PORCENTAJE_OCUPACION" : 91.99
	},
	{
		"CATEGORIA" : "N51 JEFE SERVICIO UMH  80",
		"PLAZAS_OCUPADAS" : 1329,
		"PLAZAS_VACANTES" : 385,
		"DIFERENCIA" : 944,
		"PORCENTAJE_OCUPACION" : 77.54
	},
	{
		"CATEGORIA" : "MED TRAS PAC URGENCIA  80",
		"PLAZAS_OCUPADAS" : 144,
		"PLAZAS_VACANTES" : 187,
		"DIFERENCIA" : -43,
		"PORCENTAJE_OCUPACION" : 43.50
	},
	{
		"CATEGORIA" : "N52 COORD CLINICO UMH  80",
		"PLAZAS_OCUPADAS" : 495,
		"PLAZAS_VACANTES" : 101,
		"DIFERENCIA" : 394,
		"PORCENTAJE_OCUPACION" : 83.05
	},
	{
		"CATEGORIA" : "N53 JEF DEPTO CLIN UMAE80",
		"PLAZAS_OCUPADAS" : 560,
		"PLAZAS_VACANTES" : 70,
		"DIFERENCIA" : 490,
		"PORCENTAJE_OCUPACION" : 88.89
	},
	{
		"CATEGORIA" : "N51 JEFE SERVICIOS UMF 80",
		"PLAZAS_OCUPADAS" : 1350,
		"PLAZAS_VACANTES" : 66,
		"DIFERENCIA" : 1284,
		"PORCENTAJE_OCUPACION" : 95.34
	},
	{
		"CATEGORIA" : "N51 JEF SPPSTIMSS UMH 2NIV 80",
		"PLAZAS_OCUPADAS" : 106,
		"PLAZAS_VACANTES" : 59,
		"DIFERENCIA" : 47,
		"PORCENTAJE_OCUPACION" : 64.24
	},
	{
		"CATEGORIA" : "N53 COORD CL TURNO UMH 80",
		"PLAZAS_OCUPADAS" : 557,
		"PLAZAS_VACANTES" : 48,
		"DIFERENCIA" : 509,
		"PORCENTAJE_OCUPACION" : 92.07
	},
	{
		"CATEGORIA" : "MED TRAS PAC TERAP INT 80",
		"PLAZAS_OCUPADAS" : 12,
		"PLAZAS_VACANTES" : 20,
		"DIFERENCIA" : -8,
		"PORCENTAJE_OCUPACION" : 37.50
	},
	{
		"CATEGORIA" : "N51 JEFE SERVICIO CONSULT EXT UMH 80",
		"PLAZAS_OCUPADAS" : 62,
		"PLAZAS_VACANTES" : 20,
		"DIFERENCIA" : 42,
		"PORCENTAJE_OCUPACION" : 75.61
	},
	{
		"CATEGORIA" : "N55 JEFE DIV MED UMAE  80",
		"PLAZAS_OCUPADAS" : 190,
		"PLAZAS_VACANTES" : 19,
		"DIFERENCIA" : 171,
		"PORCENTAJE_OCUPACION" : 90.91
	},
	{
		"CATEGORIA" : "N49 DIR UMF 4 5 Y 6   80",
		"PLAZAS_OCUPADAS" : 97,
		"PLAZAS_VACANTES" : 13,
		"DIFERENCIA" : 84,
		"PORCENTAJE_OCUPACION" : 88.18
	},
	{
		"CATEGORIA" : "N57 COORD PROG MED     80",
		"PLAZAS_OCUPADAS" : 219,
		"PLAZAS_VACANTES" : 13,
		"DIFERENCIA" : 206,
		"PORCENTAJE_OCUPACION" : 94.40
	},
	{
		"CATEGORIA" : "N55 SUBD MED UMH A     80",
		"PLAZAS_OCUPADAS" : 105,
		"PLAZAS_VACANTES" : 11,
		"DIFERENCIA" : 94,
		"PORCENTAJE_OCUPACION" : 90.52
	},
	{
		"CATEGORIA" : "N55 INVEST TITULAR A   80",
		"PLAZAS_OCUPADAS" : 28,
		"PLAZAS_VACANTES" : 10,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 73.68
	},
	{
		"CATEGORIA" : "N50 INVEST ASOCIADO B  80",
		"PLAZAS_OCUPADAS" : 43,
		"PLAZAS_VACANTES" : 9,
		"DIFERENCIA" : 34,
		"PORCENTAJE_OCUPACION" : 82.69
	},
	{
		"CATEGORIA" : "N53 DIRECTOR UMH D     80",
		"PLAZAS_OCUPADAS" : 65,
		"PLAZAS_VACANTES" : 9,
		"DIFERENCIA" : 56,
		"PORCENTAJE_OCUPACION" : 87.84
	},
	{
		"CATEGORIA" : "N56 DIRECTOR UMH A     80",
		"PLAZAS_OCUPADAS" : 78,
		"PLAZAS_VACANTES" : 8,
		"DIFERENCIA" : 70,
		"PORCENTAJE_OCUPACION" : 90.70
	},
	{
		"CATEGORIA" : "N53 INVEST ASOCIADO D  80",
		"PLAZAS_OCUPADAS" : 19,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 73.08
	},
	{
		"CATEGORIA" : "N53 SUBDIR MED UMH C   80",
		"PLAZAS_OCUPADAS" : 43,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 36,
		"PORCENTAJE_OCUPACION" : 86.00
	},
	{
		"CATEGORIA" : "N54 SUBDIR MED UMH B   80",
		"PLAZAS_OCUPADAS" : 47,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 40,
		"PORCENTAJE_OCUPACION" : 87.04
	},
	{
		"CATEGORIA" : "N52 SUBD MED UM C      80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 58.82
	},
	{
		"CATEGORIA" : "N51 COORD HOSP DON ORG Y TEJ UMH",
		"PLAZAS_OCUPADAS" : 50,
		"PLAZAS_VACANTES" : 7,
		"DIFERENCIA" : 43,
		"PORCENTAJE_OCUPACION" : 87.72
	},
	{
		"CATEGORIA" : "N51 MEDICO ESP ST      80",
		"PLAZAS_OCUPADAS" : 48,
		"PLAZAS_VACANTES" : 6,
		"DIFERENCIA" : 42,
		"PORCENTAJE_OCUPACION" : 88.89
	},
	{
		"CATEGORIA" : "N49 INVEST ASOCIADO A  80",
		"PLAZAS_OCUPADAS" : 28,
		"PLAZAS_VACANTES" : 6,
		"DIFERENCIA" : 22,
		"PORCENTAJE_OCUPACION" : 82.35
	},
	{
		"CATEGORIA" : "N52 INVEST ASOCIADO C  80",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 11,
		"PORCENTAJE_OCUPACION" : 76.19
	},
	{
		"CATEGORIA" : "N54 MED SUP HOSPITALES 80",
		"PLAZAS_OCUPADAS" : 35,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 30,
		"PORCENTAJE_OCUPACION" : 87.50
	},
	{
		"CATEGORIA" : "N52 SUBDIR MEDICO UMF  80",
		"PLAZAS_OCUPADAS" : 60,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 55,
		"PORCENTAJE_OCUPACION" : 92.31
	},
	{
		"CATEGORIA" : "N62 JEFE AREA MEDICA   80",
		"PLAZAS_OCUPADAS" : 132,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 127,
		"PORCENTAJE_OCUPACION" : 96.35
	},
	{
		"CATEGORIA" : "N52 JEFE DIVISION UMH  80",
		"PLAZAS_OCUPADAS" : 11,
		"PLAZAS_VACANTES" : 5,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 68.75
	},
	{
		"CATEGORIA" : "N54 DIRECTOR UMF 1     80",
		"PLAZAS_OCUPADAS" : 98,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 94,
		"PORCENTAJE_OCUPACION" : 96.08
	},
	{
		"CATEGORIA" : "N54 DIRECTOR UMH C     80",
		"PLAZAS_OCUPADAS" : 48,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 44,
		"PORCENTAJE_OCUPACION" : 92.31
	},
	{
		"CATEGORIA" : "N56 INVEST TITULAR B   80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 9,
		"PORCENTAJE_OCUPACION" : 76.47
	},
	{
		"CATEGORIA" : "N53 DIRECTOR  UMF 2    80",
		"PLAZAS_OCUPADAS" : 156,
		"PLAZAS_VACANTES" : 4,
		"DIFERENCIA" : 152,
		"PORCENTAJE_OCUPACION" : 97.50
	},
	{
		"CATEGORIA" : "N58 DIR ED INV SA UMAE 80",
		"PLAZAS_OCUPADAS" : 22,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 19,
		"PORCENTAJE_OCUPACION" : 88.00
	},
	{
		"CATEGORIA" : "N56 MED SUP LIDER 80",
		"PLAZAS_OCUPADAS" : 39,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 36,
		"PORCENTAJE_OCUPACION" : 92.86
	},
	{
		"CATEGORIA" : "N55 INVEST TIT A MED   80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : -3,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N51 PROF MED CENT INV ED FORM DOC 80",
		"PLAZAS_OCUPADAS" : 20,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 86.96
	},
	{
		"CATEGORIA" : "N56 COORD AUX GEST MED D3YD4 80",
		"PLAZAS_OCUPADAS" : 29,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 26,
		"PORCENTAJE_OCUPACION" : 90.63
	},
	{
		"CATEGORIA" : "N58 INVEST TITULAR C   80",
		"PLAZAS_OCUPADAS" : 12,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 9,
		"PORCENTAJE_OCUPACION" : 80.00
	},
	{
		"CATEGORIA" : "N52 DIRECTOR UMF 3     80",
		"PLAZAS_OCUPADAS" : 143,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 140,
		"PORCENTAJE_OCUPACION" : 97.95
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) PLAN ENL INST D3 Y D4",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 83.33
	},
	{
		"CATEGORIA" : "N54 MED SUP EPIDEMIOLOGO 80",
		"PLAZAS_OCUPADAS" : 31,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 28,
		"PORCENTAJE_OCUPACION" : 91.18
	},
	{
		"CATEGORIA" : "N55 DIRECTOR UMH B     80",
		"PLAZAS_OCUPADAS" : 47,
		"PLAZAS_VACANTES" : 3,
		"DIFERENCIA" : 44,
		"PORCENTAJE_OCUPACION" : 94.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED INVEST D3YD4 80",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 88.89
	},
	{
		"CATEGORIA" : "N54 MED SUP MED FAM 80",
		"PLAZAS_OCUPADAS" : 40,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 38,
		"PORCENTAJE_OCUPACION" : 95.24
	},
	{
		"CATEGORIA" : "N53 INVEST ASOC D MED  80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : -2,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N60 JEFE UNID INV MED  80",
		"PLAZAS_OCUPADAS" : 12,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 85.71
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) PREV ATN SAL D1 Y D2",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 13,
		"PORCENTAJE_OCUPACION" : 88.24
	},
	{
		"CATEGORIA" : "N51 PROFESOR(A) MEDICO(A) CESIECQ 80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N52 JEFE CLIN SAL TRAB 80",
		"PLAZAS_OCUPADAS" : 13,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 11,
		"PORCENTAJE_OCUPACION" : 86.67
	},
	{
		"CATEGORIA" : "N57 COOR CLIN TUR UMAE 80",
		"PLAZAS_OCUPADAS" : 98,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 96,
		"PORCENTAJE_OCUPACION" : 98.00
	},
	{
		"CATEGORIA" : "N51 DIRECTOR UMH E     80",
		"PLAZAS_OCUPADAS" : 82,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 80,
		"PORCENTAJE_OCUPACION" : 97.62
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED SALUD TRAB D3YD4 80",
		"PLAZAS_OCUPADAS" : 30,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 28,
		"PORCENTAJE_OCUPACION" : 93.75
	},
	{
		"CATEGORIA" : "N53 JEF SPPSTIMSS UMAE 80",
		"PLAZAS_OCUPADAS" : 26,
		"PLAZAS_VACANTES" : 2,
		"DIFERENCIA" : 24,
		"PORCENTAJE_OCUPACION" : 92.86
	},
	{
		"CATEGORIA" : "N60 JEFE UNIDAD INVEST 80",
		"PLAZAS_OCUPADAS" : 12,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 11,
		"PORCENTAJE_OCUPACION" : 92.31
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED EDUCA D3YD4 80",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 94.12
	},
	{
		"CATEGORIA" : "N49 JEF AREA MED CECART80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N53 COORD HOSP DON ORG Y TEJ UMAE",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 94.12
	},
	{
		"CATEGORIA" : "JEFE AREA MEDICA NIVEL CENTRAL E0",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 5,
		"PORCENTAJE_OCUPACION" : 85.71
	},
	{
		"CATEGORIA" : "MED ESPECIALISTA PSIQUIATRA CAICE",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED SAL PUBLICA D3YD4 80",
		"PLAZAS_OCUPADAS" : 15,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 14,
		"PORCENTAJE_OCUPACION" : 93.75
	},
	{
		"CATEGORIA" : "N55 COORD AUX MED SPPSTIMSS D1YD2 80",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 94.44
	},
	{
		"CATEGORIA" : "N51 DIRECTOR DE CECART 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N55 COORD AUX ATN MED D1YD2 80",
		"PLAZAS_OCUPADAS" : 34,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 33,
		"PORCENTAJE_OCUPACION" : 97.14
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) INF AN EST D3 Y D4",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 94.44
	},
	{
		"CATEGORIA" : "N55 MED ESP PEDIATRA CAICE",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N55 COORD AUX MED SAL PUBLICA D1YD2 80",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 94.44
	},
	{
		"CATEGORIA" : "INVESTIGADOR ASOCIADO E2",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N43 MED ESP RAHB GERON CEAGE",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N55 COORD AUX MED INVEST D1YD2 80",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 94.44
	},
	{
		"CATEGORIA" : "N51 MEDICO(A) RESP PROY CICR CANCER 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N52 INVEST ASOC C MED  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N52 COOR AUX PROG M D1 80",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N52 SUBD MED UM B      80",
		"PLAZAS_OCUPADAS" : 9,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 90.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX ATN MED D3YD4 80",
		"PLAZAS_OCUPADAS" : 35,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 34,
		"PORCENTAJE_OCUPACION" : 97.22
	},
	{
		"CATEGORIA" : "N51 JEFE DEPTO CLINICO 80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 9,
		"PORCENTAJE_OCUPACION" : 90.91
	},
	{
		"CATEGORIA" : "N53 COOR AUX PROG M D2 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 0,
		"PORCENTAJE_OCUPACION" : 50.00
	},
	{
		"CATEGORIA" : "N60 DIR CENT INV B MED 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 66.67
	},
	{
		"CATEGORIA" : "N48 DIRECTOR MICROZONA 80",
		"PLAZAS_OCUPADAS" : 145,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 144,
		"PORCENTAJE_OCUPACION" : 99.32
	},
	{
		"CATEGORIA" : "JEFE UNIDAD INVEST MEDICA E0",
		"PLAZAS_OCUPADAS" : 0,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : -1,
		"PORCENTAJE_OCUPACION" : 0.00
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) SALUD TRAB D3 Y D4",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 16,
		"PORCENTAJE_OCUPACION" : 94.44
	},
	{
		"CATEGORIA" : "N55 COORD AUX MED SALUD TRAB D1YD2 80",
		"PLAZAS_OCUPADAS" : 16,
		"PLAZAS_VACANTES" : 1,
		"DIFERENCIA" : 15,
		"PORCENTAJE_OCUPACION" : 94.12
	},
	{
		"CATEGORIA" : "JEFE DIV INV SALUD UMAE E0",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N60 DIRECTOR MED UMAE 80",
		"PLAZAS_OCUPADAS" : 6,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 6,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N53 DIRECTOR UM C      80",
		"PLAZAS_OCUPADAS" : 29,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 29,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N60 JEFE(A) SERVS PREST MEDICAS D1 Y D2",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N60 COORD TECNICO A MED80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 CONFIANZA MEDICA   80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N59 COORDINADOR(A) PREV ATN SAL D3 Y D4",
		"PLAZAS_OCUPADAS" : 18,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N34 MEDICO GRAL U MED  80",
		"PLAZAS_OCUPADAS" : 8,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 8,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COOR AUX AT MED D4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 COORD AUX MED EDUCA D1YD2 80",
		"PLAZAS_OCUPADAS" : 18,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COOR REG AUX MED D480",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N62 JEFE(A) SERVS PREST MEDICAS D3 Y D4",
		"PLAZAS_OCUPADAS" : 18,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N62 DIRECTOR(A) CICR CANCER 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N60 CONFIANZA MEDICA   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "INVEST ASOC D MED E3",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N50 INVEST ASOC B MED  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N53 DIR CENT INV ED FORM DOC 80",
		"PLAZAS_OCUPADAS" : 12,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 12,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N53 DIRECTOR(A) CESIECQ 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "MEDICO NO FAMILIAR H R",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N57 COORDINADOR(A) INF AN EST D1 Y D2",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD PROGS MEDICOS NIVEL CENTRAL E0",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 MEDICO ESP CAICE 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "INVESTIGADOR ASOCIADO E3",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N58 COORDINADOR(A) GEST MEDICA D3 Y D4",
		"PLAZAS_OCUPADAS" : 18,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N57 COORDINADOR(A) GEST MEDICA D1 Y D2",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 COOR AUX PROG M D4 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N60 DIRECTOR UC UMAE    80",
		"PLAZAS_OCUPADAS" : 4,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 4,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED EPIDEMIOLOGI D3YD4 80",
		"PLAZAS_OCUPADAS" : 18,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "MEDICO(A) AUX PROY CICR CANCER E0",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 COORD AUX MED EPIDEMIOLOGI D1YD2 80",
		"PLAZAS_OCUPADAS" : 18,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "COORD AUX MEDICO DE INVESTIG E1",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 MED ESP MFR CAICE",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N52 DIRECTOR(A) CLINICA DE MAMA 80",
		"PLAZAS_OCUPADAS" : 10,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 10,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 CONFIANZA MEDICA   80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 COORD AUX GEST MED D1YD2 80",
		"PLAZAS_OCUPADAS" : 18,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 18,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 DIRECTOR(A) UNID CTROL MET AMBUL 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N52 COOR AUX DEL ST    80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N63 DIRECTOR MED UMAE 80",
		"PLAZAS_OCUPADAS" : 26,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 26,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N55 COORD ATN MED D2   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "MEDICO GENERAL U MED  80",
		"PLAZAS_OCUPADAS" : 217,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 217,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N63 CONFIANZA MEDICA 80",
		"PLAZAS_OCUPADAS" : 3,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 3,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 COORD AUX MED SPPSTIMSS D3YD4 80",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N52 DIRECTOR UM D      80",
		"PLAZAS_OCUPADAS" : 33,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 33,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N57 COORDINADOR(A) SALUD TRAB D1 Y D2",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 COORD PROG MED D2  80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N54 COOR AUX PROG M D3 80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 DIRECTOR UMF       80",
		"PLAZAS_OCUPADAS" : 41,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 41,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N60 COOR ATN MED CAICE",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N56 INVEST TIT B MED   80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N49 INVEST ASOC A MED  80",
		"PLAZAS_OCUPADAS" : 2,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 2,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N57 COORDINADOR(A) PLAN ENL INST D1 Y D2",
		"PLAZAS_OCUPADAS" : 17,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 17,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N45 MEDICO(A) AUX PROY CICR CANCER 80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "INVESTIGADOR ASOCIADO E1",
		"PLAZAS_OCUPADAS" : 41,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 41,
		"PORCENTAJE_OCUPACION" : 100.00
	},
	{
		"CATEGORIA" : "N58 INVEST TIT C MED   80",
		"PLAZAS_OCUPADAS" : 1,
		"PLAZAS_VACANTES" : 0,
		"DIFERENCIA" : 1,
		"PORCENTAJE_OCUPACION" : 100.00
	}
];
